#logging.level.org.springframework=INFO
#logging.level.org.springframework.web=INFO
#logging.level.org.springframework.security=INFO

#spring.servlet.multipart.max-file-size=4GB
#spring.servlet.multipart.max-request-size=4GB

#Tomcat thread pool size
#server.tomcat.threads.max=250

#logging.level.com.cbi.ccr=DEBUG

#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
#logging.level.com.cbi.ccr.csw.inbound.api.service=DEBUG

