<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.cbi.chc.csw</groupId>
		<artifactId>chc-ccr-clientsw</artifactId>
		<version>1.10.0</version>
	</parent>
	<artifactId>chc-ccr-clientsw-all-app</artifactId>

	<properties>
		<!-- The main class to start by executing "java -jar" -->
		<start-class>com.cbi.ccr.csw.app.CswAllApp</start-class>
		<skipTests>true</skipTests>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.cbi.chc.framework</groupId>
			<artifactId>chc-framework-micros</artifactId>
			<version>${chc-framework-version}</version>
		</dependency>

		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-poller-app</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-poller-mq</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-db-outbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-db-inbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-mq-outbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-mq-inbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-femws-outbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-femws-inbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-restful-outbound</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-dashboard-api</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-dashboard-ui</artifactId>
			<version>${project.version}</version>
		</dependency>

	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>version</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.2.0</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/classes/static/</outputDirectory>
							<resources>
								<resource>
									<directory>${project.parent.basedir}/chc-ccr-clientsw-dashboard/chc-ccr-clientsw-dashboard-ui/dist/clientsw/</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<skip>${skipTests}</skip>
					<argLine>${argLine}</argLine>
				</configuration>
			</plugin>
			<!-- Package as an executable jar/ -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>com.cbi.ccr.csw.app.CswAllApp</mainClass>
					<includeSystemScope>true</includeSystemScope>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>