server.port=40002
fixed_poller_delay=5000


# numero di thread da attivare per ogni worker
outbound_worker_threads=1
## invio multi thread verso uno o piu' worker. Potrebeb anche essere sempre ,o stesso
outbound_workers[0]=http://localhost:40001



