alter table GLOBAL_CONFIGURATION add constraint UNIQUE_GLOBAL_CONFIGURATION unique NONCLUSTERED (PROPERTY)
   WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [${DB_USER}._INDEX]
/