-- *************************************************************************
-- Sync_send
-- *************************************************************************
--/
CREATE TABLE SYNC_SEND
(
	LOCALBA_ID			VARCHAR2(12) NOT NULL,
	REMOTEBA_ID			VARCHAR2(12) NOT NULL,
	VFN					VARCHAR2(32),
	STATUS_BA			VARCHAR2(60) DEFAULT 'SUBMITTED',
	STATUS_SYNC			VARCHAR2(60),
	STCODE_BA			NUMBER(10) DEFAULT 0  NOT NULL,
	STCODE_SYNC			NUMBER(10) DEFAULT 0  NOT NULL,
	FNAME			VARCHAR2(1024)  NOT NULL,
	RETRY_CNT			NUMBER(10) DEFAULT 0,
	USERDATAREMOTE			VARCHAR2(80) NOT NULL,
	PRIORITY			NUMBER(10) DEFAULT 0,
	BAMSG_ID			VARCHAR2(30),
	MESSAGE			BLOB,
	ACCEPTTIME			DATE,
	FTSSENDTIME			DATE,
	FTSCOMPLETETIME			DATE,
	MSSENDTIME			DATE,
	MSCOMPLETETIME			DATE,
	NOTIFYTIME			DATE,
	MODTIME			DATE DEFAULT sys_extract_utc(systimestamp) NOT NULL,
	USERDATAREMOTELEN			NUMBER(10),
	TUR			VARCHAR2(16),
	MESSAGELEN			NUMBER(10),
	MESSAGETYPE			VARCHAR2(3) NOT NULL,
	CATAPPL			VARCHAR2(4),
	ERRORTIME			DATE,
	FER_SUB_FST_FTS_TMP			DATE,
	FER_SUB_LST_FTS_TMP			DATE,
	FER_DLV_FST_FTS_TMP			DATE,
	FER_DLV_LST_FTS_TMP			DATE,
	FEN_SUB_MSS_TMP			DATE,
	FEN_DLV_MSS_TMP			DATE,
	CRT_SUB_MSS_TMP			DATE,
	CRT_DLV_MSS_TMP			DATE,
	DATASETNAME			VARCHAR2(255),
	LOCAL_DATA			VARCHAR2(255),
	CERTF_REQ			NUMBER(10),
	FSIZE			NUMBER(19),
	FHASH			VARCHAR2(32),
	FBLOCKMOVED			NUMBER(10),
	FMAP			VARCHAR2(256),
	COMPLETE			NUMBER(10) DEFAULT 0,
	LAST_UPDATE			NUMBER(10),
	BA_INSERT_TIMESTAMP			DATE DEFAULT sys_extract_utc(systimestamp),
	SEND_ACCEPTED_TIMESTAMP			DATE,
	SEND_REQUEST_TIMESTAMP			DATE,
	SEND_CONFIRMED_TIMESTAMP			DATE,
	SEND_COMPLETED_TIMESTAMP			DATE,
	SEND_ERROR_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(4000),
	ID_SYNC_SEND			NUMBER(19),
	OPERATION_TIMESTAMP			DATE,
	OPERATION			VARCHAR2(10),
	REACTIVATE			VARCHAR2(10),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
    CSW_STATUS VARCHAR2(60),
    CSW_VERSION NUMBER(19) DEFAULT 0
)
	TABLESPACE CHC_CCR_OWN_DATA 
	LOB(MESSAGE) 
	STORE as BASICFILE (TABLESPACE CHC_CCR_OWN_DATA disable storage in row)
/
--/
alter table SYNC_SEND add constraint PK_SYNC_SEND
primary key (ID_SYNC_SEND)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table SYNC_SEND add constraint UK_SYNC_SEND_VFN
unique (VFN)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table SYNC_SEND add constraint SYNC_SEND_UDR_LBA_RBA
unique (USERDATAREMOTE,LOCALBA_ID,REMOTEBA_ID)
/
--/
alter table SYNC_SEND add constraint CK_SYNC_SEND_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
--/
alter table SYNC_SEND add constraint CK_SYNC_SEND_CLEANUP_TYPE
check (cleanup_type in('IRL_FMS_SND'))
/
--/
alter table SYNC_SEND add constraint CK_SYNC_SEND_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
--/
alter table SYNC_SEND add constraint CK_SYNC_SEND_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
--/
alter table SYNC_SEND add constraint CK_SYNC_SEND_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
--/
create index IDX_SYNC_SEND_1 on  SYNC_SEND(STCODE_BA,STCODE_SYNC,ID_SYNC_SEND)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SYNC_SEND_2 on  SYNC_SEND(COMPLETE,STCODE_BA,STCODE_SYNC,LAST_UPDATE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SYNC_SEND_3 on  SYNC_SEND(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace CHC_CCR_OWN_DATA
/
--/
CREATE SEQUENCE SYNC_SEND_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
/
--CREATE OR REPLACE TRIGGER TRG_SYNC_SEND_INS_UPD
--before insert or update of STCODE_BA,STCODE_SYNC on SYNC_SEND
--for each row
--declare
--	audit_enabled varchar2(100);
--	oldStcode     varchar2(30);
--begin
	-- set identity
	--begin if :new.ID_SYNC_SEND is null then SELECT SYNC_SEND_SEQ.NEXTVAL INTO :NEW.ID_SYNC_SEND FROM dual; end if; end;
--end TRG_SYNC_SEND_INS_UPD;
-- TRIGGER --
--/
CREATE OR REPLACE TRIGGER TRG_SYNC_SEND_INS_UPD
before insert or update of STCODE_BA,STCODE_SYNC on SYNC_SEND
for each row
begin
	begin if :new.ID_SYNC_SEND is null then SELECT SYNC_SEND_SEQ.NEXTVAL INTO :NEW.ID_SYNC_SEND FROM dual; end if; end;
	begin if((:new.complete is NULL or :new.complete=0) and (:old.STCODE_BA=4 and :old.STCODE_SYNC=15) and (:new.STCODE_BA=7 and :new.STCODE_SYNC=23))
  then
    :new.complete := 1;
  end if;
  end;
end TRG_SYNC_SEND_INS_UPD;
/
-- *************************************************************************
-- Sync_recv
-- *************************************************************************
--/
CREATE TABLE SYNC_RECV
(
	LOCALBA_ID			VARCHAR2(12) NOT NULL,
	REMOTEBA_ID			VARCHAR2(12) NOT NULL,
	VFN			VARCHAR2(32) NOT NULL,
	STATUS_BA			VARCHAR2(60),
	STATUS_SYNC			VARCHAR2(60),
	STCODE_BA			NUMBER(10) DEFAULT 0,
	STCODE_SYNC			NUMBER(10) DEFAULT 0,
	TIMEOUT			NUMBER(10),
	FTSRECVTIME			DATE,
	MSRECVTIME			DATE,
	FNAME			VARCHAR2(1024) NOT NULL,
	USERDATAREMOTE			VARCHAR2(80),
	PRIORITY			NUMBER(10),
	MESSAGETYPE			VARCHAR2(3),
	MODTIME			DATE,
	MESSAGE			BLOB,
	MESSAGELENGTH			NUMBER(10),
	CAT_APPLY			VARCHAR2(4),
	TUR			VARCHAR2(16),
	BAMSGID			VARCHAR2(30),
	RECEIVETIME			DATE,
	FTSINSERTTIME			DATE,
	MSCONFTIME			DATE,
	FTSDELIVTIME			DATE,
	BA_PROCESSED_TMP			DATE,
	DATASETNAME			VARCHAR2(255),
	FER_SUB_FST_FTS_TMP			DATE,
	FER_SUB_LST_FTS_TMP			DATE,
	FER_DLV_FST_FTS_TMP			DATE,
	FER_DLV_LST_FTS_TMP			DATE,
	FEN_SUB_MSS_TMP			DATE,
	FEN_DLV_MSS_TMP			DATE,
	CRT_SUB_MSS_TMP			DATE,
	CRT_DLV_MSS_TMP			DATE,
	READ_STR_FTS_TMP			DATE,
	READ_END_FTS_TMP			DATE,
	LOCAL_DATA			VARCHAR2(255),
	CERTF_REQ			NUMBER(10),
	START_RECV_GMT			DATE,
	FSIZE			INTEGER,
	FHASH			VARCHAR2(32),
	FBLOCKMOVED			NUMBER(10),
	FMAP			VARCHAR2(256),
	COMPLETE			NUMBER(10),
	LAST_UPDATE			NUMBER(10),
	READ_REQUEST_TIMESTAMP			DATE,
	READ_CONFIRMED_TIMESTAMP			DATE,
	READ_COMPLETED_TIMESTAMP			DATE,
	READ_NOTIFIED_TIMESTAMP			DATE,
	READ_ERROR_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(4000),
	FILE_FORMAT			VARCHAR2(32),
	COMPRESSION_ALGO			VARCHAR2(32),
	FAS_SEQID			NUMBER(19) NOT NULL,
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
    CSW_STATUS VARCHAR2(60)
)
	TABLESPACE CHC_CCR_OWN_DATA
	LOB(MESSAGE)
	STORE as BASICFILE (TABLESPACE CHC_CCR_OWN_DATA disable storage in row)
/
--/
alter table SYNC_RECV add constraint PK_SYNC_RECV
primary key (FAS_SEQID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table SYNC_RECV add constraint UK_SYNCRECVLOCALBAIDREMOTEB_1
unique (VFN,LOCALBA_ID,REMOTEBA_ID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table SYNC_RECV add constraint CK_SYNC_RECV_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
--/
alter table SYNC_RECV add constraint CK_SYNC_RECV_CLEANUP_TYPE
check (cleanup_type in('IRL_FMS_RCV'))
/
--/
alter table SYNC_RECV add constraint CK_SYNC_RECV_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
--/
alter table SYNC_RECV add constraint CK_SYNC_RECV_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
--/
alter table SYNC_RECV add constraint CK_SYNC_RECV_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
--/
create index IDX_SYNC_RECV_1 on  SYNC_RECV(STCODE_BA,STCODE_SYNC)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SYNC_RECV_2 on  SYNC_RECV(COMPLETE,STCODE_BA,STCODE_SYNC,LAST_UPDATE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SYNC_RECV_3 on  SYNC_RECV(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace CHC_CCR_OWN_DATA
/
--/
create sequence SYNC_RECV_SEQ start with 1 increment by  1
/
-- TRIGGER --
--/
CREATE OR REPLACE TRIGGER TRG_SYNC_RECV_INS_UPD
before insert or update of STCODE_BA,STCODE_SYNC on SYNC_RECV
for each row
begin
	if((:new.complete is NULL or :new.complete=0) and (:old.STCODE_BA=1 and :old.STCODE_SYNC=6) and (:new.STCODE_BA=2 and :new.STCODE_SYNC=15))
	then
		:new.complete := 1;
	end if;
end TRG_SYNC_RECV_INS_UPD;
/
-- *************************************************************************
-- Send_file
-- *************************************************************************
--/
CREATE TABLE SEND_FILE
(
	VFN			VARCHAR2(32) NOT NULL,
	FNAME			VARCHAR2(1024),
	LOCAL_BA			VARCHAR2(12) NOT NULL,
	REMOTE_BA			VARCHAR2(12) NOT NULL,
	STATUS			VARCHAR2(60) DEFAULT 'FILE TO BE PROCESSED' NOT NULL,
	EASSTATUS			VARCHAR2(3),
	STSCODE			NUMBER(10) DEFAULT 90 NOT NULL,
	COMPLETE			NUMBER(10) DEFAULT 0 NOT NULL,
	TRANSP_TYPE			VARCHAR2(8) DEFAULT 'EAS' NOT NULL,
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	APPL_CHECK			NUMBER(10) DEFAULT 0 NOT NULL,
	ORIGINAL_FNAME			VARCHAR2(1024),
	RETRY_CNT			NUMBER(10) DEFAULT 0,
	UPDATE_MARK			NUMBER(10),
	FSIZE			NUMBER(10),
	FMD5			VARCHAR2(32),
	FBLKMOVED			NUMBER(10),
	FILEMAP			VARCHAR2(255),
	OPERATION_TIMESTAMP			DATE,
	OPERATION			VARCHAR2(10),
	REACTIVATE			VARCHAR2(10),
	REF_DATE			VARCHAR2(6),
	ACT_REQ_TIME			VARCHAR2(12),
	EAS_ACQ_TIME			VARCHAR2(17),
	QUEUE_INS_TIME			VARCHAR2(17),
	START_TIME			VARCHAR2(17),
	EAS_COMPL_TIME			VARCHAR2(17),
	BA_PROC_TIME			VARCHAR2(12),
	EAS_ELAB_TIME			VARCHAR2(17),
	BA_INSERT_TIMESTAMP			DATE DEFAULT sys_extract_utc(systimestamp),
	SEND_ACCEPTED_TIMESTAMP			DATE,
	SEND_GFT_REQUEST_TIMESTAMP			DATE,
	SEND_REQUEST_TIMESTAMP			DATE,
	SEND_CONFIRMED_TIMESTAMP			DATE,
	SEND_COMPLETED_TIMESTAMP			DATE,
	SEND_ERROR_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(4000),
	ID_SEND_FILE			NUMBER(19) NOT NULL,
	APPLICATIVE_DATA_FIELD			VARCHAR2(80),
	APPLICATIVE_DATA_FIELD_LENGTH			NUMBER(10),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_FS			VARCHAR2(128 CHAR),
    CSW_STATUS VARCHAR2(60),
    CSW_VERSION NUMBER(19) DEFAULT 0,
    FTS_INTERFACE VARCHAR2(2) DEFAULT 'DB'
)
	TABLESPACE CHC_CCR_OWN_DATA
/
--/
alter table SEND_FILE add constraint PK_SEND_FILE
primary key (ID_SEND_FILE)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table SEND_FILE add constraint UK_SEND_FILE_VFN
unique (VFN)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table SEND_FILE add constraint CK_SEND_FILE_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
--/
alter table SEND_FILE add constraint CK_SEND_FILE_CLEANUP_TYPE
check (cleanup_type in('IRL_FTS_SND'))
/
--/
alter table SEND_FILE add constraint CK_SEND_FILE_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
--/
alter table SEND_FILE add constraint CK_SEND_FILE_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NULL)
	OR (LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_FS IS NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256'))
	OR (LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NOT NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
--/
create index IDX_SEND_FILE_AB on  SEND_FILE(APPL_CHECK,STSCODE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SEND_FILE_1 on  SEND_FILE(STSCODE,ID_SEND_FILE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SEND_FILE_2 on  SEND_FILE(COMPLETE,STSCODE,LASTUPDATE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_SEND_FILE_3 on  SEND_FILE(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace CHC_CCR_OWN_DATA
/
--/
CREATE SEQUENCE SEND_FILE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
/
--CREATE OR REPLACE TRIGGER TRG_SEND_FILE_INS_UPD
--before insert or update of STSCODE on SEND_FILE
--for each row
--declare
--	audit_enabled varchar2(100);
--	oldStcode     varchar2(30);
--begin
	-- set identity
	--begin if :new.ID_SEND_FILE is null then SELECT SEND_FILE_SEQ.NEXTVAL INTO :NEW.ID_SEND_FILE FROM dual; end if; end;
--end TRG_SEND_FILE_INS_UPD;
-- TRIGGER --
--/
CREATE OR REPLACE TRIGGER TRG_SEND_FILE_INS_UPD
before insert or update of APPL_CHECK,STSCODE on SEND_FILE
for each row
begin 
        begin if :new.ID_SEND_FILE is null then SELECT SEND_FILE_SEQ.NEXTVAL INTO :NEW.ID_SEND_FILE FROM dual; end if; end;
        begin if(:new.complete=0 and :new.appl_check<>0 and :new.stscode=305)
	then
		:new.complete := 1;
	end if;
	end;
end TRG_SEND_FILE_INS_UPD;
/
-- *************************************************************************
-- Recv_file
-- *************************************************************************
--/
CREATE TABLE RECV_FILE
(
	VFN			VARCHAR2(32) NOT NULL,
	FNAME			VARCHAR2(1024),
	LOCAL_BA			VARCHAR2(12) NOT NULL,
	REMOTE_BA			VARCHAR2(12) NOT NULL,
	STATUS			VARCHAR2(60) NOT NULL,
	EASSTATUS			VARCHAR2(3),
	STSCODE			NUMBER(10) NOT NULL,
	COMPLETE			NUMBER(10) NOT NULL,
	TRANSP_TYPE			VARCHAR2(8) NOT NULL,
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	APPL_CHECK			NUMBER(10) NOT NULL,
	ORIGINAL_FNAME			VARCHAR2(1024),
	RETRY_CNT			NUMBER(10),
	UPDATE_MARK			NUMBER(10),
	FSIZE			NUMBER(10),
	FMD5			VARCHAR2(32),
	FBLKMOVED			NUMBER(10),
	FILEMAP			VARCHAR2(255),
	REF_DATE			VARCHAR2(6),
	ACT_REQ_TIME			VARCHAR2(12),
	EAS_ACQ_TIME			VARCHAR2(17),
	QUEUE_INS_TIME			VARCHAR2(17),
	START_TIME			VARCHAR2(17),
	EAS_COMPL_TIME			VARCHAR2(17),
	FIRST_DEL_TIME			VARCHAR2(17),
	LAST_DEL_TIME			VARCHAR2(17),
	FIRST_READ_TIME			VARCHAR2(17),
	LAST_READ_TIME			VARCHAR2(17),
	BA_PROC_TIME			VARCHAR2(12),
	EAS_ELAB_TIME			VARCHAR2(17),
	RECV_REQUEST_TIMESTAMP			DATE,
	RECV_ERROR_TIMESTAMP			DATE,
	RECV_COMPLETE_TIMESTAMP			DATE,
	RECV_DELIVERED_TIMESTAMP			DATE,
	FAS_SEQID			NUMBER(19) NOT NULL,
	STATUS_INFO			VARCHAR2(4000),
	APPLICATIVE_DATA_FIELD			VARCHAR2(80),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_FS			VARCHAR2(128 CHAR),
    CSW_STATUS VARCHAR2(60),
    FTS_INTERFACE VARCHAR2(2) DEFAULT 'DB'
)
	TABLESPACE CHC_CCR_OWN_DATA
/
--/
alter table RECV_FILE add constraint PK_RECV_FILE
primary key (FAS_SEQID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table RECV_FILE add constraint UK_RECVFILEVFNLOCALBAREMOTEBA
unique (VFN,LOCAL_BA,REMOTE_BA)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table RECV_FILE add constraint CK_RECV_FILE_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
--/
alter table RECV_FILE add constraint CK_RECV_FILE_CLEANUP_TYPE
check (cleanup_type in('IRL_FTS_RCV'))
/
--/
alter table RECV_FILE add constraint CK_RECV_FILE_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
--/
alter table RECV_FILE add constraint CK_RECV_FILE_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NULL)
	OR (LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_FS IS NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256'))
	OR (LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NOT NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
--/
create index IDX_RECV_FILE_AB on  RECV_FILE(APPL_CHECK,STSCODE,LOCAL_BA)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_RECV_FILE_1 on  RECV_FILE(STSCODE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_RECV_FILE_2 on  RECV_FILE(COMPLETE,STSCODE,LASTUPDATE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_RECV_FILE_3 on  RECV_FILE(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace CHC_CCR_OWN_DATA
/
--/
create sequence RECV_FILE_SEQ start with 1 increment by  1
/
-- TRIGGER --
--/
CREATE OR REPLACE TRIGGER TRG_RECV_FILE_INS_UPD
before insert or update of APPL_CHECK,STSCODE on RECV_FILE
for each row
begin
	if(:new.complete=0 and :new.appl_check<>0 and :new.stscode=511)
	then
		:new.complete := 1;
	end if;
end TRG_RECV_FILE_INS_UPD;
/
-- *************************************************************************
-- Fas_msg_send
-- *************************************************************************
--/
CREATE TABLE FAS_MSG_SEND
(
	LOCAL_BA			VARCHAR2(12) NOT NULL,
	REMOTE_BA			VARCHAR2(12) NOT NULL,
	MSG_TYPE			VARCHAR2(3),
	CAT_APPL			VARCHAR2(4),
	TUR			VARCHAR2(16),
	MSGID			VARCHAR2(30) NOT NULL,
	REMOTE_REF			VARCHAR2(80),
	PRIORITY			NUMBER(10) DEFAULT 0,
	CERTF_REQ			NUMBER(10),
	STSCODE			NUMBER(10) DEFAULT 0 NOT NULL,
	STATUS			VARCHAR2(256) DEFAULT 'NEW TRAFFIC',
	EASSTATUS			VARCHAR2(3),
	COMPLETE			NUMBER(10) DEFAULT 0,
	APPL_CHECK			NUMBER(10) DEFAULT 0 NOT NULL,
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	UPDATE_MARK			NUMBER(10),
	SEQID			NUMBER(19),
	MSGSIZE			NUMBER(10),
	MAB			BLOB,
	BA_REQ_TIME			VARCHAR2(17),
	BAR_ACQ_TIME			VARCHAR2(17),
	FEMSI_RETRY_NUMBER			NUMBER(10),
	FIRST_EAS_SUB_TIME			VARCHAR2(17),
	LAST_EAS_SUB_TIME			VARCHAR2(17),
	FER_SUB_TIME			VARCHAR2(17),
	FEN_DEL_TIME			VARCHAR2(17),
	FER_DEL_TIME			VARCHAR2(17),
	BA_INSERT_TIMESTAMP			DATE DEFAULT sys_extract_utc(systimestamp),
	LOAD_TIMESTAMP			DATE,
	SEND_REQ_TIMESTAMP			DATE,
	SEND_ERR_TIMESTAMP			DATE,
	SEND_CNF_TIMESTAMP			DATE,
	SEND_SC_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(4000),
	FAS_SEQID			NUMBER(19) NOT NULL,
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	NET_MSGID			VARCHAR2(16),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
    CSW_STATUS VARCHAR2(60),
    CSW_VERSION NUMBER(19) DEFAULT 0,
    CSW_RETRY_CNT NUMBER(10) DEFAULT 0
)
	TABLESPACE CHC_CCR_OWN_DATA
	LOB(MAB)
	STORE as BASICFILE (TABLESPACE CHC_CCR_OWN_DATA disable storage in row)
/ 
--/
alter table FAS_MSG_SEND add constraint PK_FAS_MSG_SEND
primary key (FAS_SEQID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table FAS_MSG_SEND add constraint UK_FASMSGSENDR6CUFASMSGSEND
unique (LOCAL_BA,MSGID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
--/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_CLEANUP_TYPE
check (cleanup_type in('IRL_MSS_SND'))
/
--/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
--/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
--/
create index IDX_FAS_MSG_SEND_AB on  FAS_MSG_SEND(APPL_CHECK,STSCODE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_FAS_MSG_SEND_1 on  FAS_MSG_SEND(STSCODE,FAS_SEQID)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_FAS_MSG_SEND_2 on  FAS_MSG_SEND(COMPLETE,STSCODE,LASTUPDATE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_FAS_MSG_SEND_3 on  FAS_MSG_SEND(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace CHC_CCR_OWN_DATA
/
--/
CREATE SEQUENCE FAS_MSG_SEND_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
/
--CREATE OR REPLACE TRIGGER TRG_FAS_MSG_SEND_INS_UPD
--before insert or update of STSCODE on FAS_MSG_SEND
--for each row
--declare
--	audit_enabled varchar2(100);
--	oldStcode     varchar2(30);
--begin
	-- set identity
	--begin if :new.FAS_SEQID is null then SELECT FAS_MSG_SEND_SEQ.NEXTVAL INTO :NEW.FAS_SEQID FROM dual; end if; end;
--end TRG_FAS_MSG_SEND_INS_UPD;
-- TRIGGER --
--/
CREATE OR REPLACE TRIGGER TRG_FAS_MSG_SEND_INS_UPD
before insert or update of APPL_CHECK,STSCODE on FAS_MSG_SEND
for each row
begin
        begin if :new.FAS_SEQID is null then SELECT FAS_MSG_SEND_SEQ.NEXTVAL INTO :NEW.FAS_SEQID FROM dual; end if; end;
	begin if(:new.complete=0 and :new.appl_check<>0 and :new.stscode=1140)
	then
		:new.complete := 1;
	end if;
	end;
end TRG_FAS_MSG_SEND_UPD;
/
-- *************************************************************************
-- Fas_msg_recv
-- *************************************************************************
--/
CREATE TABLE FAS_MSG_RECV
(
	LOCAL_BA			VARCHAR2(12) NOT NULL,
	REMOTE_BA			VARCHAR2(12) NOT NULL,
	MSG_TYPE			VARCHAR2(3),
	CAT_APPL			VARCHAR2(4),
	TUR			VARCHAR2(16),
	MSGID			VARCHAR2(30) NOT NULL,
	REMOTE_REF			VARCHAR2(80),
	PRIORITY			NUMBER(10),
	CERTF_REQ			NUMBER(10),
	STSCODE			NUMBER(10) NOT NULL,
	STATUS			VARCHAR2(60),
	EASSTATUS			VARCHAR2(3),
	COMPLETE			NUMBER(10),
	APPL_CHECK			NUMBER(10) NOT NULL,
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	UPDATE_MARK			NUMBER(10),
	SEQID			NUMBER(19) NOT NULL,
	MSGSIZE			NUMBER(10),
	MAB			BLOB,
	BA_REQ_TIME			VARCHAR2(17),
	BAR_ACQ_TIME			VARCHAR2(17),
	EAS_SUB_TIME			VARCHAR2(17),
	FER_SUB_TIME			VARCHAR2(17),
	FEN_DEL_TIME			VARCHAR2(17),
	FER_DEL_TIME			VARCHAR2(17),
	FIRST_BAR_SUB_TIME			VARCHAR2(17),
	LAST_BAR_SUB_TIME			VARCHAR2(17),
	RECV_RNC_TIMESTAMP			DATE,
	RECV_RC_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(4000),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	NET_MSGID			VARCHAR2(16),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
    CSW_STATUS VARCHAR2(60)
)
	TABLESPACE CHC_CCR_OWN_DATA
	LOB(MAB)
	STORE as BASICFILE (TABLESPACE CHC_CCR_OWN_DATA disable storage in row)
/
--/
alter table FAS_MSG_RECV add constraint PK_FAS_MSG_RECV
primary key (SEQID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table FAS_MSG_RECV add constraint UK_FASMSGRECVR6CUFASMSGRECV
unique (LOCAL_BA,MSGID)
using index tablespace CHC_CCR_OWN_DATA
/
--/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
--/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_CLEANUP_TYPE
check (cleanup_type in('IRL_MSS_RCV'))
/
--/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
--/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
--/
create index IDX_FAS_MSG_RECV_AB on  FAS_MSG_RECV(APPL_CHECK,STSCODE,LOCAL_BA)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_FAS_MSG_RECV_1 on  FAS_MSG_RECV(STSCODE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_FAS_MSG_RECV_2 on  FAS_MSG_RECV(COMPLETE,STSCODE,LASTUPDATE)
 tablespace CHC_CCR_OWN_DATA
/
--/
create index IDX_FAS_MSG_RECV_3 on  FAS_MSG_RECV(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace CHC_CCR_OWN_DATA
/
--/
create sequence FAS_MSG_RECV_SEQ start with 1 increment by  1
/
-- TRIGGER --
--/
CREATE OR REPLACE TRIGGER TRG_FAS_MSG_RECV_INS_UPD
before insert or update of APPL_CHECK,STSCODE on FAS_MSG_RECV
for each row
begin
	if(:new.complete=0 and :new.appl_check<>0 and :new.stscode=1220)
	then
		:new.complete := 1;
	end if;
end TRG_FAS_MSG_RECV_INS_UPD;
/

