--ALTER TABLE SYNC_SEND ADD CSW_STATUS VARCHAR(60)
/
--ALTER TABLE SYNC_SEND ADD CSW_VERSION bigint DEFAULT 0
/
--ALTER TABLE SYNC_SEND ALTER COLUMN STATUS_INFO TYPE VARCHAR(4000)
/
--ALTER TABLE SYNC_RECV ADD CSW_STATUS VARCHAR(60)
/
ALTER TABLE SYNC_RECV ALTER COLUMN STATUS_INFO TYPE VARCHAR(4000)
/
ALTER TABLE SEND_FILE ADD CSW_STATUS VARCHAR(60)
/
ALTER TABLE SEND_FILE ALTER COLUMN STATUS_INFO TYPE VARCHAR(4000)
/
ALTER TABLE SEND_FILE ADD CSW_VERSION bigint DEFAULT 0
/
ALTER TABLE RECV_FILE ADD CSW_STATUS VARCHAR(60)
/
ALTER TABLE RECV_FILE ALTER COLUMN STATUS_INFO TYPE VARCHAR(4000)
/
ALTER TABLE FAS_MSG_SEND ADD CSW_STATUS VARCHAR(60)
/
ALTER TABLE FAS_MSG_SEND ALTER COLUMN STATUS_INFO TYPE VARCHAR(4000)
/
ALTER TABLE FAS_MSG_SEND ADD CSW_VERSION bigint DEFAULT 0
/
ALTER TABLE FAS_MSG_SEND ADD CSW_RETRY_CNT int4 DEFAULT 0
/
ALTER TABLE FAS_MSG_RECV ADD CSW_STATUS VARCHAR(60)
/
ALTER TABLE FAS_MSG_RECV ALTER COLUMN STATUS_INFO TYPE VARCHAR(4000)
/