--ALTER TABLE SEND_FILE ADD FTS_INTERFACE VARCHAR(2) DEFAULT 'DB'
/
--ALTER TABLE RECV_FILE ADD FTS_INTERFACE VARCHAR(2) DEFAULT 'DB'
/
--ALTER TABLE ADD_ON_CONFIGURATION_FTS ADD RCV_PATH VARCHAR(255)
/
--alter table ADD_ON_CONFIGURATION_FTS add constraint SND_PATH_CONSTRAIN unique (SND_PATH)
/
alter table ADD_ON_CONFIGURATION_FTS add constraint RCV_PATH_CONSTRAIN unique (RCV_PATH)
/