ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA ALTER COLUMN LOCALBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA ALTER COLUMN REMOTEBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA ALTER COLUMN LOCALBAID DROP NOT NULL
/		
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA ALTER COLUMN REMOTEBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA ALTER COLUMN LOCALBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA ALTER COLUMN REMOTEBAID DROP NOT NULL
/
--ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA ALTER COLUMN SND_COMPLETION_ALGO SET DEFAULT true
/
--ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA ALTER COLUMN RCV_COMPLETION_ALGO SET DEFAULT true
/
--ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA ALTER COLUMN SND_COMPLETION_ALGO SET DEFAULT true
/
--ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA ALTER COLUMN RCV_COMPLETION_ALGO SET DEFAULT true
/
--ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA ALTER COLUMN SND_COMPLETION_ALGO SET DEFAULT true
/
--ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA ALTER COLUMN RCV_COMPLETION_ALGO SET DEFAULT true
/