 create table FMS_RECV_MQI (
       ID bigint not null,
       LOCALBA_ID varchar(12) not null,
       REMOTEBA_ID varchar(12) not null,
       STATUS varchar(255),
       CSW_STATUS varchar(255),
       CORRELATION_ID varchar(30),
       VFN varchar(32) not null,
       FSIZE bigint not null,
       QUEUE_FILENAME varchar(48),
       GROUP_ID varchar(48),
       LINE_SEPARATOR varchar(255),
       RECORD_FORMAT varchar(255),
       MAX_REC_LEN int4,
       SND_CHAR_TYPE varchar(255) not null,
       RCV_CHAR_TYPE varchar(255),
       ADF_LEN int4,
       ADF varchar(80),
       UDR_LEN int4 not null,
       UDR varchar(80) not null,
       TUR varchar(16),
       MESSAGETYPE varchar(3) not null,
       CATAPPL varchar(4),
       LOCAL_BA_DATA varchar(80),
       NET_FILE_SIZE bigint,
       TRANSFER_ID varchar(16) not null,
       FNAME varchar(1024),
       FILE_DIGEST_ALG varchar(8),
       FILE_DIGEST_LEN bigint,
       FILE_DIGEST varchar(128),
       MSG_DIGEST_ALG varchar(8),
       MSG_DIGEST_LEN bigint,
       MSG_DIGEST varchar(128),
       MESSAGELEN int4 not null,
       MESSAGE bytea,
       LOCAL_AUTH_INFO_ALG varchar(8),
       LOCAL_AUTH_INFO_LEN bigint,
       LOCAL_AUTH_INFO varchar(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPT_TMS DATE,
       START_READ_TMS DATE,
       END_READ_TMS DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       HOST_FIRST_SUB_TMS DATE,
       FER_SUB_TIME DATE,
       FEN_SUB_TMS DATE,
       HOST_FIRST_DEL_TMS DATE,
       FIRST_BA_DLV_TMS DATE,
       COMPLETE int4,
       PRIMITIVE_ERROR varchar(50),
       REJECT_REASON int4,
       STATUS_INFO varchar(1024),
       CSW_RETRY_CNT int4,
       CSW_VERSION bigint,
       primary key (ID)
    )
/
       create table FMS_SEND_MQI (
       ID_SYNC_SEND bigint not null,
       LOCALBA_ID varchar(12) not null,
       REMOTEBA_ID varchar(12) not null,
       STATUS varchar(255),
       CSW_STATUS varchar(255),
       SEND_TYPE int4,
       CORRELATION_ID varchar(30),
       VFN varchar(32) not null,
       FSIZE bigint not null,
       QUEUE_FILENAME varchar(48) not null,
       GROUP_ID varchar(48) not null,
       LINE_SEPARATOR varchar(255) not null,
       RECORD_FORMAT varchar(255),
       MAX_REC_LEN int4,
       CHAR_TYPE varchar(255) not null,
       ADF_LEN int4,
       ADF varchar(80),
       UDR_LEN int4 not null,
       UDR varchar(80) not null,
       TUR varchar(16),
       MESSAGETYPE varchar(3) not null,
       CATAPPL varchar(4),
       LOCAL_BA_DATA varchar(80),
       NET_FILE_SIZE bigint,
       TRANSFER_ID varchar(16),
       FNAME varchar(1024),
       FILE_DIGEST_ALG varchar(8),
       FILE_DIGEST_LEN bigint,
       FILE_DIGEST varchar(128),
       MSG_DIGEST_ALG varchar(8),
       MSG_DIGEST_LEN bigint,
       MSG_DIGEST varchar(128),
       MESSAGELEN int4 not null,
       MESSAGE bytea,
       LOCAL_AUTH_INFO_ALG varchar(8),
       LOCAL_AUTH_INFO_LEN bigint,
       LOCAL_AUTH_INFO varchar(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPTTIME DATE,
       START_CREATE_TIMESTAMP DATE,
       END_CREATE_TIMESTAMP DATE,
       ERROR_TIMESTAMP DATE,
       SENDTIME DATE,
       COMPLETETIME DATE,
       NOTIFYTIME DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       SEND_ERROR_TIMESTAMP DATE,
       COMPLETE int4,
       PRIMITIVE_ERROR varchar(50),
       REJECT_REASON int4,
       STATUS_INFO varchar(1024),
       NEG_DETAIL_OPER varchar(1024),
       CSW_RETRY_CNT int4,
       CSW_VERSION bigint,
       primary key (ID_SYNC_SEND)
    )
/
   create table FTS_RECV_MQI (
       ID bigint not null,
       LOCALBA_ID varchar(12) not null,
       REMOTEBA_ID varchar(12) not null,
       STATUS varchar(255),
       CSW_STATUS varchar(255),
       CORRELATION_ID varchar(30),
       VFN varchar(32) not null,
       FSIZE bigint,
       QUEUE_FILENAME varchar(48),
       GROUP_ID varchar(48),
       LINE_SEPARATOR varchar(255),
       RECORD_FORMAT varchar(255),
       MAX_REC_LEN int4,
       SND_CHAR_TYPE varchar(255) not null,
       RCV_CHAR_TYPE varchar(255),
       ADF_LEN int4,
       ADF varchar(80),
       TUR varchar(16),
       LOCAL_BA_DATA varchar(80),
       NET_FILE_SIZE bigint not null,
       TRANSFER_ID varchar(16) not null,
       FNAME varchar(1024),
       FILE_DIGEST_ALG varchar(8),
       FILE_DIGEST_LEN bigint,
       FILE_DIGEST varchar(128),
       LOCAL_AUTH_INFO_ALG varchar(8),
       LOCAL_AUTH_INFO_LEN bigint,
       LOCAL_AUTH_INFO varchar(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPT_TMS DATE,
       START_READ_TMS DATE,
       END_READ_TMS DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       HOST_FIRST_SUB_TMS DATE,
       FER_SUB_TIME DATE,
       FEN_SUB_TMS DATE,
       HOST_FIRST_DEL_TMS DATE,
       FIRST_BA_DLV_TMS DATE,
       COMPLETE int4,
       PRIMITIVE_ERROR varchar(50),
       REJECT_REASON int4,
       STATUS_INFO varchar(1024),
       CSW_RETRY_CNT int4,
       CSW_VERSION bigint,
       primary key (ID)
    )
/
    create table FTS_SEND_MQI (
       ID_SEND_FILE bigint not null,
       LOCALBA_ID varchar(12) not null,
       REMOTEBA_ID varchar(12) not null,
       STATUS varchar(255),
       CSW_STATUS varchar(255),
       SEND_TYPE int4,
       CORRELATION_ID varchar(30),
       VFN varchar(32) not null,
       FSIZE bigint not null,
       QUEUE_FILENAME varchar(48) not null,
       GROUP_ID varchar(48) not null,
       LINE_SEPARATOR varchar(255) not null,
       RECORD_FORMAT varchar(255),
       MAX_REC_LEN int4,
       CHAR_TYPE varchar(255) not null,
       ADF_LEN int4,
       ADF varchar(80),
       MESSAGETYPE varchar(3),
       LOCAL_BA_DATA varchar(80),
       NET_FILE_SIZE bigint,
       TRANSFER_ID varchar(16),
       FNAME varchar(1024),
       FILE_DIGEST_ALG varchar(8),
       FILE_DIGEST_LEN bigint,
       FILE_DIGEST varchar(128),
       LOCAL_AUTH_INFO_ALG varchar(8),
       LOCAL_AUTH_INFO_LEN bigint,
       LOCAL_AUTH_INFO varchar(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPTTIME DATE,
       START_CREATE_TIMESTAMP DATE,
       END_CREATE_TIMESTAMP DATE,
       ERROR_TIMESTAMP DATE,
       SENDTIME DATE,
       COMPLETETIME DATE,
       NOTIFYTIME DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       SEND_ERROR_TIMESTAMP DATE,
       COMPLETE int4,
       PRIMITIVE_ERROR varchar(50),
       REJECT_REASON int4,
       STATUS_INFO varchar(1024),
       NEG_DETAIL_OPER varchar(1024),
       CSW_RETRY_CNT int4,
       CSW_VERSION bigint,
       primary key (ID_SEND_FILE)
    )
/
     create table MSS_RECV_MQI (
       ID bigint not null,
       LOCALBA_ID varchar(12) not null,
       REMOTEBA_ID varchar(12) not null,
       STATUS varchar(255),
       CSW_STATUS varchar(255),
       MSGID varchar(30) not null,
--       MSGIDR varchar(30) not null,
       PRIORITY int4 not null,
       UDR_LEN int4,
       UDR varchar(80),
       TUR varchar(16),
       MESSAGETYPE varchar(3) not null,
       CATAPPL varchar(4),
       MSG_DIGEST_ALG varchar(8),
       MSG_DIGEST_LEN bigint,
       MSG_DIGEST varchar(128),
       MESSAGE bytea,
       LOCAL_AUTH_INFO_ALG varchar(8),
       LOCAL_AUTH_INFO_LEN bigint,
       LOCAL_AUTH_INFO varchar(128),
       CSW_INSERT_TIMESTAMP DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       HOST_FIRST_SUB_TMS DATE,
       FER_SUB_TIME DATE,
       FEN_SUB_TMS DATE,
       HOST_FIRST_DEL_TMS DATE,
       FIRST_BA_DLV_TMS DATE,
       COMPLETE int4,
       PRIMITIVE_ERROR varchar(50),
       REJECT_REASON int4,
       STATUS_INFO varchar(1024),
       CSW_RETRY_CNT int4,
       CSW_VERSION bigint,
       primary key (ID)
    )
/
    create table MSS_SEND_MQI (
       FAS_SEQID bigint not null,
       LOCALBA_ID varchar(12) not null,
       REMOTEBA_ID varchar(12) not null,
       STATUS varchar(255),
       CSW_STATUS varchar(255),
       LOCAL_BA_DATA varchar(100),
--       MSGID varchar(30) not null,
       PRIORITY int4 not null,
       TUR varchar(16),
       MSG_TYPE varchar(3) not null,
       CAT_APPL varchar(4),
       CORRELATION_ID varchar(30),
       UDR_LEN int4,
       UDR varchar(80),
       MSG_DIGEST_ALG varchar(8),
       MSG_DIGEST_LEN bigint,
       MSG_DIGEST varchar(128),
       MESSAGELEN int4 not null,
       MESSAGE bytea,
       LOCAL_AUTH_INFO_ALG varchar(8),
       LOCAL_AUTH_INFO_LEN bigint,
       LOCAL_AUTH_INFO varchar(128),
       CSW_INSERT_TIMESTAMP DATE,
       BA_REQ_TMS DATE,
       ACCEPTTIME DATE,
       SENDTIME DATE,
       COMPLETETIME DATE,
       NOTIFYTIME DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       SEND_ERROR_TIMESTAMP DATE,
       COMPLETE int4,
       PRIMITIVE_ERROR varchar(50),
       REJECT_REASON int4,
       STATUS_INFO varchar(1024),
       CSW_RETRY_CNT int4,
       CSW_VERSION bigint,
       primary key (FAS_SEQID)
    )
/
create sequence SYNC_SEND_SEQ_MQ start with 1 increment by  1
/
create sequence SYNC_RECV_SEQ_MQ start with 1 increment by  1
/
create sequence SEND_FILE_SEQ_MQ start with 1 increment by  1
/
create sequence RECV_FILE_SEQ_MQ start with 1 increment by  1
/
create sequence FAS_MSG_SEND_SEQ_MQ start with 1 increment by  1
/
create sequence FAS_MSG_RECV_SEQ_MQ start with 1 increment by  1
/
