ALTER TABLE USERS ADD SECRET_ANSWER_ONE VARCHAR(255)
/
ALTER TABLE USERS ADD SECRET_ANSWER_TWO VARCHAR(255)
/
ALTER TABLE USERS ADD SECRET_RESPONSE_ONE VARCHAR(255)
/
ALTER TABLE USERS ADD SECRET_RESPONSE_TWO VARCHAR(255)
/