ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA DROP COLUMN LEFT_LAU_KEY
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA DROP COLUMN RIGHT_LAU_KEY
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA DROP COLUMN LAU_FORMAT
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA ADD LAU_KEY VARCHAR(255)
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA DROP COLUMN LEFT_LAU_KEY
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA DROP COLUMN RIGHT_LAU_KEY
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA DROP COLUMN LAU_FORMAT
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA ADD LAU_KEY VARCHAR(255)
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA DROP COLUMN LEFT_LAU_KEY
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA DROP COLUMN RIGHT_LAU_KEY
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA DROP COLUMN LAU_FORMAT
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA ADD LAU_KEY VARCHAR(255)
/