ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA ALTER COLUMN LAU_ENABLED SET DEFAULT false
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA ALTER COLUMN LAU_ENABLED SET DEFAULT false
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA ALTER COLUMN LAU_ENABLED SET DEFAULT false
/