ALTER TABLE ADD_ON_CONFIGURATION_FTS DROP CONSTRAINT RCV_PATH_CONSTRAIN
/
ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA ALTER COLUMN LOCALBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA ALTER COLUMN REMOTEBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA ALTER COLUMN LOCALBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA ALTER COLUMN REMOTEBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA ALTER COLUMN LOCALBAID DROP NOT NULL
/
ALTER TABLE CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA ALTER COLUMN REMOTEBAID DROP NOT NULL
/

alter table if exists CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID);
/
alter table if exists CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID);
/
alter table if exists CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID);
/