ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA
ADD COLUMN HUB_CODE_PAGE VARCHAR(255),
ADD COLUMN HUB_LINE_SEPARATOR VARCHAR(255)
/

ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA
ADD COLUMN HUB_CODE_PAGE VARCHAR(255),
ADD COLUMN HUB_LINE_SEPARATOR VARCHAR(255)
/


ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA
ADD COLUMN HUB_CODE_PAGE VARCHAR(255),
ADD COLUMN HUB_LINE_SEPARATOR VARCHAR(255),
ADD COLUMN RCV_RECORD_FORMAT VARCHAR(255),
ADD COLUMN RCV_MAX_REC_LENGHT int4
/

 ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA
ADD COLUMN HUB_CODE_PAGE VARCHAR(255),
ADD COLUMN HUB_LINE_SEPARATOR VARCHAR(255),
ADD COLUMN RCV_RECORD_FORMAT VARCHAR(255),
ADD COLUMN RCV_MAX_REC_LENGHT int4
/
