DROP SEQUENCE CHC_CCR_OWN_OBJ.seq_ba_url;

DROP TABLE CHC_CCR_OWN_OBJ.ba_url CASCADE CONSTRAINTS;

DROP TABLE CHC_CCR_OWN_OBJ.ccr_fms_message CASCADE CONSTRAINTS;    
  
DROP INDEX CHC_CCR_OWN_OBJ.idx_fms_message;

DROP TABLE CHC_CCR_OWN_OBJ.ccr_fts_message CASCADE CONSTRAINTS;

DROP INDEX CHC_CCR_OWN_OBJ.idx_fts_message;

DROP TABLE CHC_CCR_OWN_OBJ.ccr_mss_message CASCADE CONSTRAINTS;

DROP INDEX CHC_CCR_OWN_OBJ.idx_mss_message;

