#spring.datasource.url=jdbc:oracle:thin:@//chc_database:1521/XE
#spring.datasource.username=ccr
#spring.datasource.password=ccr

#spring.datasource.url=jdbc:postgresql://chc_database:5432/ccr
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#spring.liquibase.change-log=classpath:db/changelog/ccr-changelog-master.yaml


#spring.datasource.url=jdbc:oracle:thin:@//poddb02-pesi-scan.cloudblue.local:1521/chccores_pry
#spring.datasource.username=CHC_CCR_OWN_OBJ
#spring.datasource.password=PEFKQZCF