ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA ALTER COLUMN SND_CODE_PAGE SET NOT NULL;
/
ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA ALTER COLUMN SND_LINE_SEPARATOR SET NOT NULL;
/
ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA ALTER COLUMN SND_RECORD_FORMAT SET NOT NULL;
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA ALTER COLUMN SND_CODE_PAGE SET NOT NULL;
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA ALTER COLUMN SND_LINE_SEPARATOR SET NOT NULL;
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA ALTER COLUMN SND_RECORD_FORMAT SET NOT NULL;
/