spring:
  profiles:
    active: orch
  cloud: 
    config: 
      import-check: 
        enabled: 'false'

server:
  port: '60005'
    
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: DEBUG
          nodeValue: INFO
        security: INFO
    com:
      cbi: DEBUG
      

eureka:
  client:
    enabled: false

    # from Ochestrator to CCR
ccr_exchange: chc_cmd_orc2_exchange
ccr_routing_key: chc_cmd_orc2ccr

# used Only by the Orchestrator Simulator
orchestrator_queue: chc_cmd_ccr2orc_queue
spring.rabbitmq.username: chcadmin
spring.rabbitmq.password: chcint
