package com.cbi.ccr.csw.domain.csw;

public enum ServiceRole {
	POLLER, POLLER_ADDON, POLLER_MQ,
	BATCH_OUTBOUND_WORKER, 
	BATCH_INBOUND_WORKER, 
	SOAP_OUTBOUND_FACADE, 
	SOAP_INBOUND_WORKER, 
	REST_OUTBOUND_FACADE, 
	DASHBOARD,
	MQ
}
