

ibm.mq.tls.enabled=false

ibm.mq.keyStore=keystore/clientkey.jks
ibm.mq.keyStorePassword=changeit

ibm.mq.ssl-cipher-spec=TLS_RSA_WITH_AES_128_CBC_SHA256

ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.ADMIN.SVRCONN
ibm.mq.connName=chc_imbmq(1414)
ibm.mq.user=admin
ibm.mq.password=passw0rd
