ALTER TABLE CHC_CCR_OWN_OBJ.ccr_fms_message ADD (qtm VARCHAR2(255), csc VARCHAR2(255) );
ALTER TABLE CHC_CCR_OWN_OBJ.ccr_fts_message ADD (qtm VARCHAR2(255), csc VARCHAR2(255) );
ALTER TABLE CHC_CCR_OWN_OBJ.ccr_mss_message ADD (qtm VARCHAR2(255), csc VARCHAR2(255) );