
# Tomcat thread pool size
#server.tomcat.threads.max=10
# this must be the same of server.tomcat.threads.max
#thread_pool_size=10
# add SOAP_OUTBOUND_FACADE to spring.profiles.active into application.properties of chc-ccr-clientsw-all-app




