-- *************************************************************************
-- conf_route_interface
-- *************************************************************************
create sequence SEQ_CONF_ROUTE_INTERFACE start with 1 increment by  1
/
create table CONF_ROUTE_INTERFACE (
       id number(19,0) not null,
        INTERFACE varchar2(255 char) not null,
        LOCALBA_ID varchar2(12 char) not null,
        REMOTEBA_ID varchar2(12 char) not null,
        SERVICE varchar2(255 char) not null,
        primary key (id))
/
alter table CONF_ROUTE_INTERFACE add constraint UNIQUE_CONF_ROUTE_INTERFACE unique (LOCALBA_ID, REMOTEBA_ID, INTERFACE, SERVICE)
/
-- *************************************************************************
-- add_on_configuration_fts
-- *************************************************************************
create sequence seq_add_on_configuration_fts_localba_remoteba start with 1 increment by  1
/
create table ADD_ON_CONFIGURATION_FTS (
        id number(19,0) not null,
		LOCALBAID VARCHAR2(12) not null,
        REMOTEBAID VARCHAR2(12) not null,
        SND_PATH VARCHAR2(255) not null,
        SENDING_PREFIX VARCHAR2(255),
        ERROR_PREFIX VARCHAR2(255),
        SENT_PREFIX VARCHAR2(255),
        ERRORDELIVER_PREFIX VARCHAR2(255),
        primary key (id))
/
alter table ADD_ON_CONFIGURATION_FTS add constraint UNIQUE_ADD_ON_CONFIGURATION_FTS unique (LOCALBAID, REMOTEBAID)
/

-- *************************************************************************
-- configuration_fms_localba_remoteba
-- *************************************************************************
create sequence seq_configuration_fms_localba_remoteba start with 1 increment by  1
/
create table CONFIGURATION_FMS_LOCALBA_REMOTEBA (
        id number(19,0) not null,
		LOCALBAID VARCHAR2(12) not null,
		REMOTEBAID VARCHAR2(12) not null,
        INTERFACE_TYPE VARCHAR2(255) not null,
        LAU_ENABLED NUMBER(1),
        LAU_FORMAT VARCHAR2(255),
        LEFT_LAU_KEY VARCHAR2(255),
        RCV_CODE_PAGE VARCHAR2(255),
        RCV_COMPLETION_ALGO NUMBER(1),
        RCV_DIGEST_FILE_ALG NUMBER(10),
        RCV_DSN_CREATION_ALGO NUMBER(10),
        RCV_DSN_PREFIX VARCHAR2(44),
        RCV_LINE_SEPARATOR VARCHAR2(255),
        RCV_RECORD_FORMAT VARCHAR2(255),
        RCV_MAX_REC_LENGHT NUMBER(10),
        RCV_PATH VARCHAR2(255),
        RIGHT_LAU_KEY VARCHAR2(255),
        SND_CODE_PAGE VARCHAR2(255),
        SND_COMPLETION_ALGO NUMBER(1),
        SND_LINE_SEPARATOR VARCHAR2(255),
        SND_MAX_REC_LENGHT NUMBER(10),
        SND_PATH VARCHAR2(255),
        SND_RECORD_FORMAT VARCHAR2(255),
         primary key (id))
/
alter table CONFIGURATION_FMS_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_FMS_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID)
/
-- *************************************************************************
-- configuration_fts_localba_remoteba
-- *************************************************************************
create sequence seq_configuration_fts_localba_remoteba start with 1 increment by  1
/
create table CONFIGURATION_FTS_LOCALBA_REMOTEBA (
        id number(19,0) not null,
		LOCALBAID VARCHAR2(12) not null,
		REMOTEBAID VARCHAR2(12) not null,
        INTERFACE_TYPE VARCHAR2(255) not null,
        LAU_ENABLED NUMBER(1),
        LAU_FORMAT VARCHAR2(255),
        LEFT_LAU_KEY VARCHAR2(255),
        RCV_CODE_PAGE VARCHAR2(255),
        RCV_COMPLETION_ALGO NUMBER(1),
        RCV_DIGEST_FILE_ALG NUMBER(10),
        RCV_DSN_CREATION_ALGO NUMBER(10),
        RCV_DSN_PREFIX VARCHAR2(44),
        RCV_LINE_SEPARATOR VARCHAR2(255),
        RCV_RECORD_FORMAT VARCHAR2(255),
        RCV_MAX_REC_LENGHT NUMBER(10),
        RCV_PATH VARCHAR2(255),
        RIGHT_LAU_KEY VARCHAR2(255),
        SND_CODE_PAGE VARCHAR2(255),
        SND_COMPLETION_ALGO NUMBER(1),
        SND_LINE_SEPARATOR VARCHAR2(255),
        SND_MAX_REC_LENGHT NUMBER(10),
        SND_PATH VARCHAR2(255),
        SND_RECORD_FORMAT VARCHAR2(255),
         primary key (id))
/
alter table CONFIGURATION_FTS_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_FTS_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID)
/
-- *************************************************************************
-- configuration_mss_localba_remoteba
-- *************************************************************************
create sequence seq_configuration_mss_localba_remoteba start with 1 increment by  1
/
create table CONFIGURATION_MSS_LOCALBA_REMOTEBA (
        id number(19,0) not null,
        INTERFACE_TYPE VARCHAR2(255) not null,
        LOCALBAID VARCHAR2(12) not null,
		REMOTEBAID VARCHAR2(12) not null,
        SND_COMPLETION_ALGO NUMBER(1),
        RCV_COMPLETION_ALGO NUMBER(1),
        LAU_ENABLED NUMBER(1),
        LAU_FORMAT VARCHAR2(255),
        LEFT_LAU_KEY VARCHAR2(255),
        RIGHT_LAU_KEY VARCHAR2(255),
         primary key (id))
/
alter table CONFIGURATION_MSS_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_MSS_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID)
/
-- *************************************************************************
-- Sync_send
-- *************************************************************************
CREATE TABLE SYNC_SEND
(
	LOCALBA_ID			VARCHAR2(12),
	REMOTEBA_ID			VARCHAR2(12),
	VFN					VARCHAR2(32),
	STATUS_BA			VARCHAR2(60) DEFAULT 'SUBMITTED',
	STATUS_SYNC			VARCHAR2(60),
	STCODE_BA			NUMBER(10) DEFAULT 0,
	STCODE_SYNC			NUMBER(10) DEFAULT 0,
	FNAME			VARCHAR2(1024),
	RETRY_CNT			NUMBER(10) DEFAULT 0,
	USERDATAREMOTE			VARCHAR2(80),
	PRIORITY			NUMBER(10) DEFAULT 0,
	BAMSG_ID			VARCHAR2(30),
	MESSAGE			BLOB,
	ACCEPTTIME			DATE,
	FTSSENDTIME			DATE,
	FTSCOMPLETETIME			DATE,
	MSSENDTIME			DATE,
	MSCOMPLETETIME			DATE,
	NOTIFYTIME			DATE,
	MODTIME			DATE DEFAULT sys_extract_utc(systimestamp),
	USERDATAREMOTELEN			NUMBER(10),
	TUR			VARCHAR2(16),
	MESSAGELEN			NUMBER(10),
	MESSAGETYPE			VARCHAR2(3),
	CATAPPL			VARCHAR2(4),
	ERRORTIME			DATE,
	FER_SUB_FST_FTS_TMP			DATE,
	FER_SUB_LST_FTS_TMP			DATE,
	FER_DLV_FST_FTS_TMP			DATE,
	FER_DLV_LST_FTS_TMP			DATE,
	FEN_SUB_MSS_TMP			DATE,
	FEN_DLV_MSS_TMP			DATE,
	CRT_SUB_MSS_TMP			DATE,
	CRT_DLV_MSS_TMP			DATE,
	DATASETNAME			VARCHAR2(255),
	LOCAL_DATA			VARCHAR2(255),
	CERTF_REQ			NUMBER(10),
	FSIZE			NUMBER(19),
	FHASH			VARCHAR2(32),
	FBLOCKMOVED			NUMBER(10),
	FMAP			VARCHAR2(256),
	COMPLETE			NUMBER(10) DEFAULT 0,
	LAST_UPDATE			NUMBER(10),
	BA_INSERT_TIMESTAMP			DATE DEFAULT sys_extract_utc(systimestamp),
	SEND_ACCEPTED_TIMESTAMP			DATE,
	SEND_REQUEST_TIMESTAMP			DATE,
	SEND_CONFIRMED_TIMESTAMP			DATE,
	SEND_COMPLETED_TIMESTAMP			DATE,
	SEND_ERROR_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(1024),
	ID_SYNC_SEND			NUMBER(19),
	OPERATION_TIMESTAMP			DATE,
	OPERATION			VARCHAR2(10),
	REACTIVATE			VARCHAR2(10),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE',
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR))
	TABLESPACE ${DB_USER}_TABLE 
	LOB(MESSAGE) 
	STORE as BASICFILE (TABLESPACE ${DB_USER}_LOB disable storage in row)
/
alter table SYNC_SEND add constraint PK_SYNC_SEND
primary key (ID_SYNC_SEND)
using index tablespace ${DB_USER}_INDEX
/
alter table SYNC_SEND add constraint UK_SYNC_SEND_VFN
unique (VFN)
using index tablespace ${DB_USER}_INDEX
/
alter table SYNC_SEND add constraint SYNC_SEND_UDR_LBA_RBA
unique (USERDATAREMOTE,LOCALBA_ID,REMOTEBA_ID)
/
alter table SYNC_SEND add constraint CK_SYNC_SEND_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
alter table SYNC_SEND add constraint CK_SYNC_SEND_CLEANUP_TYPE
check (cleanup_type in('IRL_FMS_SND'))
/
alter table SYNC_SEND add constraint CK_SYNC_SEND_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
alter table SYNC_SEND add constraint CK_SYNC_SEND_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
alter table SYNC_SEND add constraint CK_SYNC_SEND_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
create index IDX_SYNC_SEND_1 on  SYNC_SEND(STCODE_BA,STCODE_SYNC,ID_SYNC_SEND)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SYNC_SEND_2 on  SYNC_SEND(COMPLETE,STCODE_BA,STCODE_SYNC,LAST_UPDATE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SYNC_SEND_3 on  SYNC_SEND(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace ${DB_USER}_INDEX
/
ALTER TABLE SYNC_SEND MODIFY (CLEANUP_STATUS NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (LOCALBA_ID NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (REMOTEBA_ID NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (STCODE_BA NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (STCODE_SYNC NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (FNAME NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (USERDATAREMOTE NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (MODTIME NOT NULL)
/
ALTER TABLE SYNC_SEND MODIFY (MESSAGETYPE NOT NULL)
/
CREATE SEQUENCE SYNC_SEND_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
/
CREATE OR REPLACE TRIGGER TRG_SYNC_SEND_INS_UPD
before insert or update of STCODE_BA,STCODE_SYNC on SYNC_SEND
for each row
--declare
--	audit_enabled varchar2(100);
--	oldStcode     varchar2(30);
begin
	-- set identity
	begin if :new.ID_SYNC_SEND is null then SELECT SYNC_SEND_SEQ.NEXTVAL INTO :NEW.ID_SYNC_SEND FROM dual; end if; end;
end TRG_SYNC_SEND_INS_UPD;
/
-- *************************************************************************
-- Sync_recv
-- *************************************************************************
CREATE TABLE SYNC_RECV
(
	LOCALBA_ID			VARCHAR2(12),
	REMOTEBA_ID			VARCHAR2(12),
	VFN			VARCHAR2(32),
	STATUS_BA			VARCHAR2(60),
	STATUS_SYNC			VARCHAR2(60),
	STCODE_BA			NUMBER(10) DEFAULT 0,
	STCODE_SYNC			NUMBER(10) DEFAULT 0,
	TIMEOUT			NUMBER(10),
	FTSRECVTIME			DATE,
	MSRECVTIME			DATE,
	FNAME			VARCHAR2(1024),
	USERDATAREMOTE			VARCHAR2(80),
	PRIORITY			NUMBER(10),
	MESSAGETYPE			VARCHAR2(3),
	MODTIME			DATE,
	MESSAGE			BLOB,
	MESSAGELENGTH			NUMBER(10),
	CAT_APPLY			VARCHAR2(4),
	TUR			VARCHAR2(16),
	BAMSGID			VARCHAR2(30),
	RECEIVETIME			DATE,
	FTSINSERTTIME			DATE,
	MSCONFTIME			DATE,
	FTSDELIVTIME			DATE,
	BA_PROCESSED_TMP			DATE,
	DATASETNAME			VARCHAR2(255),
	FER_SUB_FST_FTS_TMP			DATE,
	FER_SUB_LST_FTS_TMP			DATE,
	FER_DLV_FST_FTS_TMP			DATE,
	FER_DLV_LST_FTS_TMP			DATE,
	FEN_SUB_MSS_TMP			DATE,
	FEN_DLV_MSS_TMP			DATE,
	CRT_SUB_MSS_TMP			DATE,
	CRT_DLV_MSS_TMP			DATE,
	READ_STR_FTS_TMP			DATE,
	READ_END_FTS_TMP			DATE,
	LOCAL_DATA			VARCHAR2(255),
	CERTF_REQ			NUMBER(10),
	START_RECV_GMT			DATE,
	FSIZE			INTEGER,
	FHASH			VARCHAR2(32),
	FBLOCKMOVED			NUMBER(10),
	FMAP			VARCHAR2(256),
	COMPLETE			NUMBER(10),
	LAST_UPDATE			NUMBER(10),
	READ_REQUEST_TIMESTAMP			DATE,
	READ_CONFIRMED_TIMESTAMP			DATE,
	READ_COMPLETED_TIMESTAMP			DATE,
	READ_NOTIFIED_TIMESTAMP			DATE,
	READ_ERROR_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(1024),
	FILE_FORMAT			VARCHAR2(32),
	COMPRESSION_ALGO			VARCHAR2(32),
	FAS_SEQID			NUMBER(19),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE',
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR))
	TABLESPACE ${DB_USER}_TABLE
	LOB(MESSAGE)
	STORE as BASICFILE (TABLESPACE ${DB_USER}_LOB disable storage in row)
/
alter table SYNC_RECV add constraint PK_SYNC_RECV
primary key (FAS_SEQID)
using index tablespace ${DB_USER}_INDEX
/
alter table SYNC_RECV add constraint UK_SYNCRECVLOCALBAIDREMOTEB_1
unique (VFN,LOCALBA_ID,REMOTEBA_ID)
using index tablespace ${DB_USER}_INDEX
/
alter table SYNC_RECV add constraint CK_SYNC_RECV_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
alter table SYNC_RECV add constraint CK_SYNC_RECV_CLEANUP_TYPE
check (cleanup_type in('IRL_FMS_RCV'))
/
alter table SYNC_RECV add constraint CK_SYNC_RECV_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
alter table SYNC_RECV add constraint CK_SYNC_RECV_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
alter table SYNC_RECV add constraint CK_SYNC_RECV_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
create index IDX_SYNC_RECV_1 on  SYNC_RECV(STCODE_BA,STCODE_SYNC)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SYNC_RECV_2 on  SYNC_RECV(COMPLETE,STCODE_BA,STCODE_SYNC,LAST_UPDATE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SYNC_RECV_3 on  SYNC_RECV(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace ${DB_USER}_INDEX
--
-- TRIGGER DA INSERIRE
--
/
ALTER TABLE SYNC_RECV MODIFY (LOCALBA_ID NOT NULL)
/
ALTER TABLE SYNC_RECV MODIFY (REMOTEBA_ID NOT NULL)
/
ALTER TABLE SYNC_RECV MODIFY (VFN NOT NULL)
/
ALTER TABLE SYNC_RECV MODIFY (FAS_SEQID NOT NULL)
/
ALTER TABLE SYNC_RECV MODIFY (CLEANUP_STATUS NOT NULL)
/
ALTER TABLE SYNC_RECV MODIFY (FNAME NOT NULL)
/
-- *************************************************************************
-- Send_file
-- *************************************************************************
CREATE TABLE SEND_FILE
(
	VFN			VARCHAR2(32),
	FNAME			VARCHAR2(1024),
	LOCAL_BA			VARCHAR2(12),
	REMOTE_BA			VARCHAR2(12),
	STATUS			VARCHAR2(60) DEFAULT 'FILE TO BE PROCESSED',
	EASSTATUS			VARCHAR2(3),
	STSCODE			NUMBER(10) DEFAULT 90,
	COMPLETE			NUMBER(10) DEFAULT 0,
	TRANSP_TYPE			VARCHAR2(8) DEFAULT 'EAS',
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	APPL_CHECK			NUMBER(10) DEFAULT 0,
	ORIGINAL_FNAME			VARCHAR2(1024),
	RETRY_CNT			NUMBER(10) DEFAULT 0,
	UPDATE_MARK			NUMBER(10),
	FSIZE			NUMBER(10),
	FMD5			VARCHAR2(32),
	FBLKMOVED			NUMBER(10),
	FILEMAP			VARCHAR2(255),
	OPERATION_TIMESTAMP			DATE,
	OPERATION			VARCHAR2(10),
	REACTIVATE			VARCHAR2(10),
	REF_DATE			VARCHAR2(6),
	ACT_REQ_TIME			VARCHAR2(12),
	EAS_ACQ_TIME			VARCHAR2(17),
	QUEUE_INS_TIME			VARCHAR2(17),
	START_TIME			VARCHAR2(17),
	EAS_COMPL_TIME			VARCHAR2(17),
	BA_PROC_TIME			VARCHAR2(12),
	EAS_ELAB_TIME			VARCHAR2(17),
	BA_INSERT_TIMESTAMP			DATE DEFAULT sys_extract_utc(systimestamp),
	SEND_ACCEPTED_TIMESTAMP			DATE,
	SEND_GFT_REQUEST_TIMESTAMP			DATE,
	SEND_REQUEST_TIMESTAMP			DATE,
	SEND_CONFIRMED_TIMESTAMP			DATE,
	SEND_COMPLETED_TIMESTAMP			DATE,
	SEND_ERROR_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(1024),
	ID_SEND_FILE			NUMBER(19),
	APPLICATIVE_DATA_FIELD			VARCHAR2(80),
	APPLICATIVE_DATA_FIELD_LENGTH			NUMBER(10),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE',
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_FS			VARCHAR2(128 CHAR))
	TABLESPACE ${DB_USER}_TABLE
/
alter table SEND_FILE add constraint PK_SEND_FILE
primary key (ID_SEND_FILE)
using index tablespace ${DB_USER}_INDEX
/
alter table SEND_FILE add constraint UK_SEND_FILE_VFN
unique (VFN)
using index tablespace ${DB_USER}_INDEX
/
alter table SEND_FILE add constraint CK_SEND_FILE_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
alter table SEND_FILE add constraint CK_SEND_FILE_CLEANUP_TYPE
check (cleanup_type in('IRL_FTS_SND'))
/
alter table SEND_FILE add constraint CK_SEND_FILE_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
alter table SEND_FILE add constraint CK_SEND_FILE_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NULL)
	OR (LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_FS IS NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256'))
	OR (LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NOT NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
create index IDX_SEND_FILE_AB on  SEND_FILE(APPL_CHECK,STSCODE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SEND_FILE_1 on  SEND_FILE(STSCODE,ID_SEND_FILE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SEND_FILE_2 on  SEND_FILE(COMPLETE,STSCODE,LASTUPDATE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_SEND_FILE_3 on  SEND_FILE(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace ${DB_USER}_INDEX
/
CREATE SEQUENCE SEND_FILE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
/
CREATE OR REPLACE TRIGGER TRG_SEND_FILE_INS_UPD
before insert or update of STSCODE on SEND_FILE
for each row
--declare
--	audit_enabled varchar2(100);
--	oldStcode     varchar2(30);
begin
	-- set identity
	begin if :new.ID_SEND_FILE is null then SELECT SEND_FILE_SEQ.NEXTVAL INTO :NEW.ID_SEND_FILE FROM dual; end if; end;
end TRG_SEND_FILE_INS_UPD;
/
ALTER TABLE SEND_FILE MODIFY (VFN NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (LOCAL_BA NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (REMOTE_BA NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (STATUS NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (STSCODE NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (COMPLETE NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (TRANSP_TYPE NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (APPL_CHECK NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (ID_SEND_FILE NOT NULL)
/
ALTER TABLE SEND_FILE MODIFY (CLEANUP_STATUS NOT NULL)
/
-- *************************************************************************
-- Recv_file
-- *************************************************************************
CREATE TABLE RECV_FILE
(
	VFN			VARCHAR2(32),
	FNAME			VARCHAR2(1024),
	LOCAL_BA			VARCHAR2(12),
	REMOTE_BA			VARCHAR2(12),
	STATUS			VARCHAR2(60),
	EASSTATUS			VARCHAR2(3),
	STSCODE			NUMBER(10),
	COMPLETE			NUMBER(10),
	TRANSP_TYPE			VARCHAR2(8),
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	APPL_CHECK			NUMBER(10),
	ORIGINAL_FNAME			VARCHAR2(1024),
	RETRY_CNT			NUMBER(10),
	UPDATE_MARK			NUMBER(10),
	FSIZE			NUMBER(10),
	FMD5			VARCHAR2(32),
	FBLKMOVED			NUMBER(10),
	FILEMAP			VARCHAR2(255),
	REF_DATE			VARCHAR2(6),
	ACT_REQ_TIME			VARCHAR2(12),
	EAS_ACQ_TIME			VARCHAR2(17),
	QUEUE_INS_TIME			VARCHAR2(17),
	START_TIME			VARCHAR2(17),
	EAS_COMPL_TIME			VARCHAR2(17),
	FIRST_DEL_TIME			VARCHAR2(17),
	LAST_DEL_TIME			VARCHAR2(17),
	FIRST_READ_TIME			VARCHAR2(17),
	LAST_READ_TIME			VARCHAR2(17),
	BA_PROC_TIME			VARCHAR2(12),
	EAS_ELAB_TIME			VARCHAR2(17),
	RECV_REQUEST_TIMESTAMP			DATE,
	RECV_ERROR_TIMESTAMP			DATE,
	RECV_COMPLETE_TIMESTAMP			DATE,
	RECV_DELIVERED_TIMESTAMP			DATE,
	FAS_SEQID			NUMBER(19),
	STATUS_INFO			VARCHAR2(1024),
	APPLICATIVE_DATA_FIELD			VARCHAR2(80),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE',
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	FILE_DIGEST_ALG			VARCHAR2(8 CHAR),
	FILE_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_FS			VARCHAR2(128 CHAR))
	TABLESPACE ${DB_USER}_TABLE
/
alter table RECV_FILE add constraint PK_RECV_FILE
primary key (FAS_SEQID)
using index tablespace ${DB_USER}_INDEX
/
alter table RECV_FILE add constraint UK_RECVFILEVFNLOCALBAREMOTEBA
unique (VFN,LOCAL_BA,REMOTE_BA)
using index tablespace ${DB_USER}_INDEX
/
alter table RECV_FILE add constraint CK_RECV_FILE_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
alter table RECV_FILE add constraint CK_RECV_FILE_CLEANUP_TYPE
check (cleanup_type in('IRL_FTS_RCV'))
/
alter table RECV_FILE add constraint CK_RECV_FILE_FDIGEST_ALG
check ((FILE_DIGEST_ALG IS NULL AND FILE_DIGEST IS NULL) OR (FILE_DIGEST_ALG IS NOT NULL AND FILE_DIGEST IS NOT NULL AND FILE_DIGEST_ALG in('SHA-256')))
/
alter table RECV_FILE add constraint CK_RECV_FILE_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NULL)
	OR (LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_FS IS NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256'))
	OR (LOCAL_AUTH_INFO IS NULL AND LOCAL_AUTH_INFO_FS IS NOT NULL AND LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
create index IDX_RECV_FILE_AB on  RECV_FILE(APPL_CHECK,STSCODE,LOCAL_BA)
 tablespace ${DB_USER}_INDEX
/
create index IDX_RECV_FILE_1 on  RECV_FILE(STSCODE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_RECV_FILE_2 on  RECV_FILE(COMPLETE,STSCODE,LASTUPDATE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_RECV_FILE_3 on  RECV_FILE(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace ${DB_USER}_INDEX
--
-- TRIGGER DA INSERIRE
--
/
ALTER TABLE RECV_FILE MODIFY (VFN NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (LOCAL_BA NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (REMOTE_BA NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (STATUS NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (STSCODE NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (COMPLETE NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (TRANSP_TYPE NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (APPL_CHECK NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (FAS_SEQID NOT NULL)
/
ALTER TABLE RECV_FILE MODIFY (CLEANUP_STATUS NOT NULL)
/
-- *************************************************************************
-- Fas_msg_send
-- *************************************************************************
CREATE TABLE FAS_MSG_SEND
(
	LOCAL_BA			VARCHAR2(12),
	REMOTE_BA			VARCHAR2(12),
	MSG_TYPE			VARCHAR2(3),
	CAT_APPL			VARCHAR2(4),
	TUR			VARCHAR2(16),
	MSGID			VARCHAR2(30),
	REMOTE_REF			VARCHAR2(80),
	PRIORITY			NUMBER(10) DEFAULT 0,
	CERTF_REQ			NUMBER(10),
	STSCODE			NUMBER(10) DEFAULT 0,
	STATUS			VARCHAR2(256) DEFAULT 'NEW TRAFFIC',
	EASSTATUS			VARCHAR2(3),
	COMPLETE			NUMBER(10) DEFAULT 0,
	APPL_CHECK			NUMBER(10) DEFAULT 0,
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	UPDATE_MARK			NUMBER(10),
	SEQID			NUMBER(19),
	MSGSIZE			NUMBER(10),
	MAB			BLOB,
	BA_REQ_TIME			VARCHAR2(17),
	BAR_ACQ_TIME			VARCHAR2(17),
	FEMSI_RETRY_NUMBER			NUMBER(10),
	FIRST_EAS_SUB_TIME			VARCHAR2(17),
	LAST_EAS_SUB_TIME			VARCHAR2(17),
	FER_SUB_TIME			VARCHAR2(17),
	FEN_DEL_TIME			VARCHAR2(17),
	FER_DEL_TIME			VARCHAR2(17),
	BA_INSERT_TIMESTAMP			DATE DEFAULT sys_extract_utc(systimestamp),
	LOAD_TIMESTAMP			DATE,
	SEND_REQ_TIMESTAMP			DATE,
	SEND_ERR_TIMESTAMP			DATE,
	SEND_CNF_TIMESTAMP			DATE,
	SEND_SC_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(1024),
	FAS_SEQID			NUMBER(19),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE',
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	NET_MSGID			VARCHAR2(16),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR))
	TABLESPACE ${DB_USER}_TABLE
	LOB(MAB)
	STORE as BASICFILE (TABLESPACE ${DB_USER}_LOB disable storage in row)
/ 
alter table FAS_MSG_SEND add constraint PK_FAS_MSG_SEND
primary key (FAS_SEQID)
using index tablespace ${DB_USER}_INDEX
/
alter table FAS_MSG_SEND add constraint UK_FASMSGSENDR6CUFASMSGSEND
unique (LOCAL_BA,MSGID)
using index tablespace ${DB_USER}_INDEX
/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_CLEANUP_TYPE
check (cleanup_type in('IRL_MSS_SND'))
/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
alter table FAS_MSG_SEND add constraint CK_FAS_MSG_SEND_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
create index IDX_FAS_MSG_SEND_AB on  FAS_MSG_SEND(APPL_CHECK,STSCODE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_FAS_MSG_SEND_1 on  FAS_MSG_SEND(STSCODE,FAS_SEQID)
 tablespace ${DB_USER}_INDEX
/
create index IDX_FAS_MSG_SEND_2 on  FAS_MSG_SEND(COMPLETE,STSCODE,LASTUPDATE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_FAS_MSG_SEND_3 on  FAS_MSG_SEND(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace ${DB_USER}_INDEX
/
CREATE SEQUENCE FAS_MSG_SEND_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
/
CREATE OR REPLACE TRIGGER TRG_FAS_MSG_SEND_INS_UPD
before insert or update of STSCODE on FAS_MSG_SEND
for each row
--declare
--	audit_enabled varchar2(100);
--	oldStcode     varchar2(30);
begin
	-- set identity
	begin if :new.FAS_SEQID is null then SELECT FAS_MSG_SEND_SEQ.NEXTVAL INTO :NEW.FAS_SEQID FROM dual; end if; end;
end TRG_FAS_MSG_SEND_INS_UPD;
/
ALTER TABLE FAS_MSG_SEND MODIFY (LOCAL_BA NOT NULL)
/
ALTER TABLE FAS_MSG_SEND MODIFY (REMOTE_BA NOT NULL)
/
ALTER TABLE FAS_MSG_SEND MODIFY (MSGID NOT NULL)
/
ALTER TABLE FAS_MSG_SEND MODIFY (STSCODE NOT NULL)
/
ALTER TABLE FAS_MSG_SEND MODIFY (APPL_CHECK NOT NULL)
/
ALTER TABLE FAS_MSG_SEND MODIFY (FAS_SEQID NOT NULL)
/
ALTER TABLE FAS_MSG_SEND MODIFY (CLEANUP_STATUS NOT NULL)
/
-- *************************************************************************
-- Fas_msg_recv
-- *************************************************************************
CREATE TABLE FAS_MSG_RECV
(
	LOCAL_BA			VARCHAR2(12),
	REMOTE_BA			VARCHAR2(12),
	MSG_TYPE			VARCHAR2(3),
	CAT_APPL			VARCHAR2(4),
	TUR			VARCHAR2(16),
	MSGID			VARCHAR2(30),
	REMOTE_REF			VARCHAR2(80),
	PRIORITY			NUMBER(10),
	CERTF_REQ			NUMBER(10),
	STSCODE			NUMBER(10),
	STATUS			VARCHAR2(60),
	EASSTATUS			VARCHAR2(3),
	COMPLETE			NUMBER(10),
	APPL_CHECK			NUMBER(10),
	CREATEDATE			VARCHAR2(24),
	LASTUPDATE			VARCHAR2(24),
	UPDATE_MARK			NUMBER(10),
	SEQID			NUMBER(19),
	MSGSIZE			NUMBER(10),
	MAB			BLOB,
	BA_REQ_TIME			VARCHAR2(17),
	BAR_ACQ_TIME			VARCHAR2(17),
	EAS_SUB_TIME			VARCHAR2(17),
	FER_SUB_TIME			VARCHAR2(17),
	FEN_DEL_TIME			VARCHAR2(17),
	FER_DEL_TIME			VARCHAR2(17),
	FIRST_BAR_SUB_TIME			VARCHAR2(17),
	LAST_BAR_SUB_TIME			VARCHAR2(17),
	RECV_RNC_TIMESTAMP			DATE,
	RECV_RC_TIMESTAMP			DATE,
	STATUS_INFO			VARCHAR2(1024),
	CLEANUP_STATUS			VARCHAR2(20) DEFAULT 'FREE',
	CLEANUP_LOT			NUMBER(10),
	CLEANUP_TYPE			VARCHAR2(20),
	NET_MSGID			VARCHAR2(16),
	MSG_DIGEST_ALG			VARCHAR2(8 CHAR),
	MSG_DIGEST			VARCHAR2(128 CHAR),
	LOCAL_AUTH_INFO_ALG			VARCHAR2(8 CHAR),
	LOCAL_AUTH_INFO			VARCHAR2(128 CHAR))
	TABLESPACE ${DB_USER}_TABLE
	LOB(MAB)
	STORE as BASICFILE (TABLESPACE ${DB_USER}_LOB disable storage in row)
/
alter table FAS_MSG_RECV add constraint PK_FAS_MSG_RECV
primary key (SEQID)
using index tablespace ${DB_USER}_INDEX
/
alter table FAS_MSG_RECV add constraint UK_FASMSGRECVR6CUFASMSGRECV
unique (LOCAL_BA,MSGID)
using index tablespace ${DB_USER}_INDEX
/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_CLEANUP_STATUS
check (cleanup_status in('FREE','MARKED','EXPORTED','PARTIAL_DELETED','DELETABLE'))
/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_CLEANUP_TYPE
check (cleanup_type in('IRL_MSS_RCV'))
/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_MDIGEST_ALG
check ((MSG_DIGEST_ALG IS NULL AND MSG_DIGEST IS NULL) OR (MSG_DIGEST_ALG IS NOT NULL AND MSG_DIGEST IS NOT NULL AND MSG_DIGEST_ALG in('SHA-256')))
/
alter table FAS_MSG_RECV add constraint CK_FAS_MSG_RECV_LAU_ALG
check ((LOCAL_AUTH_INFO_ALG IS NULL AND LOCAL_AUTH_INFO IS NULL) OR (LOCAL_AUTH_INFO_ALG IS NOT NULL AND LOCAL_AUTH_INFO IS NOT NULL AND LOCAL_AUTH_INFO_ALG in('HS256')))
/
create index IDX_FAS_MSG_RECV_AB on  FAS_MSG_RECV(APPL_CHECK,STSCODE,LOCAL_BA)
 tablespace ${DB_USER}_INDEX
/
create index IDX_FAS_MSG_RECV_1 on  FAS_MSG_RECV(STSCODE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_FAS_MSG_RECV_2 on  FAS_MSG_RECV(COMPLETE,STSCODE,LASTUPDATE)
 tablespace ${DB_USER}_INDEX
/
create index IDX_FAS_MSG_RECV_3 on  FAS_MSG_RECV(CLEANUP_STATUS,CLEANUP_TYPE,CLEANUP_LOT)
 tablespace ${DB_USER}_INDEX
--
-- TRIGGER DA INSERIRE
--
/
ALTER TABLE FAS_MSG_RECV MODIFY (LOCAL_BA NOT NULL)
/
ALTER TABLE FAS_MSG_RECV MODIFY (REMOTE_BA NOT NULL)
/
ALTER TABLE FAS_MSG_RECV MODIFY (MSGID NOT NULL)
/
ALTER TABLE FAS_MSG_RECV MODIFY (STSCODE NOT NULL)
/
ALTER TABLE FAS_MSG_RECV MODIFY (APPL_CHECK NOT NULL)
/
ALTER TABLE FAS_MSG_RECV MODIFY (SEQID NOT NULL)
/
ALTER TABLE FAS_MSG_RECV MODIFY (CLEANUP_STATUS NOT NULL)
/