ALTER TABLE SYNC_SEND ADD CSW_STATUS VARCHAR2(60)
/
ALTER TABLE SYNC_SEND ADD CSW_VERSION NUMBER(19) DEFAULT 0
/
ALTER TABLE SYNC_SEND MODIFY STATUS_INFO VARCHAR2(4000)
/
ALTER TABLE SYNC_RECV ADD CSW_STATUS VARCHAR2(60)
/
ALTER TABLE SYNC_RECV MODIFY STATUS_INFO VARCHAR2(4000)
/
ALTER TABLE SEND_FILE ADD CSW_STATUS VARCHAR2(60)
/
ALTER TABLE SEND_FILE MODIFY STATUS_INFO VARCHAR2(4000)
/
ALTER TABLE SEND_FILE ADD CSW_VERSION NUMBER(19) DEFAULT 0
/
ALTER TABLE RECV_FILE ADD CSW_STATUS VARCHAR2(60)
/
ALTER TABLE RECV_FILE MODIFY STATUS_INFO VARCHAR2(4000)
/
ALTER TABLE FAS_MSG_SEND ADD CSW_STATUS VARCHAR2(60)
/
ALTER TABLE FAS_MSG_SEND MODIFY STATUS_INFO VARCHAR2(4000)
/
ALTER TABLE FAS_MSG_SEND ADD CSW_VERSION NUMBER(19) DEFAULT 0
/
ALTER TABLE FAS_MSG_SEND ADD CSW_RETRY_CNT NUMBER(10) DEFAULT 0
/
ALTER TABLE FAS_MSG_RECV ADD CSW_STATUS VARCHAR2(60)
/
ALTER TABLE FAS_MSG_RECV MODIFY STATUS_INFO VARCHAR2(4000)
/