ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA MODIFY ("LOCALBAID" NULL)
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA MODIFY ("REMOTEBAID" NULL)
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA MODIFY ("LOCALBAID" NULL)
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA MODIFY ("REMOTEBAID" NULL)
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA MODIFY ("LOCALBAID" NULL)
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA MODIFY ("REMOTEBAID" NULL)
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA MODIFY "SND_COMPLETION_ALGO" DEFAULT 1
/
ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA MODIFY "RCV_COMPLETION_ALGO" DEFAULT 1
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA MODIFY "SND_COMPLETION_ALGO" DEFAULT 1
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA MODIFY "RCV_COMPLETION_ALGO" DEFAULT 1
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA MODIFY "SND_COMPLETION_ALGO" DEFAULT 1
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA MODIFY "RCV_COMPLETION_ALGO" DEFAULT 1
/