 create table FMS_RECV_MQI (
       ID number(19,0) not null,
       LOCALBA_ID varchar2(12) not null,
       REMOTEBA_ID varchar2(12) not null,
       STATUS varchar2(255),
       CSW_STATUS varchar2(255),
       CORRELATION_ID varchar2(30),
       VFN varchar2(32) not null,
       FSIZE number(19,0) not null,
       QUEUE_FILENAME varchar2(48),
       GROUP_ID varchar2(48),
       LINE_SEPARATOR varchar2(255),
       RECORD_FORMAT varchar2(255),
       MAX_REC_LEN number(10,0),
       SND_CHAR_TYPE varchar2(255) not null,
       RCV_CHAR_TYPE varchar2(255),
       ADF_LEN number(10,0),
       ADF varchar2(80),
       UDR_LEN number(10,0) not null,
       UDR varchar2(80) not null,
       TUR varchar2(16),
       MESSAGETYPE varchar2(3) not null,
       CATAPPL varchar2(4),
       LOCAL_BA_DATA varchar2(80),
       NET_FILE_SIZE number(19,0),
       TRANSFER_ID varchar2(16) not null,
       FNAME varchar2(1024),
       FILE_DIGEST_ALG varchar2(8),
       FILE_DIGEST_LEN number(19,0),
       FILE_DIGEST varchar2(128),
       MSG_DIGEST_ALG varchar2(8),
       MSG_DIGEST_LEN number(19,0),
       MSG_DIGEST varchar2(128),
       MESSAGELEN number(10,0) not null,
       MESSAGE blob,
       LOCAL_AUTH_INFO_ALG varchar2(8),
       LOCAL_AUTH_INFO_LEN number(19,0),
       LOCAL_AUTH_INFO varchar2(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPT_TMS DATE,
       START_READ_TMS DATE,
       END_READ_TMS DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       HOST_FIRST_SUB_TMS DATE,
       FER_SUB_TIME DATE,
       FEN_SUB_TMS DATE,
       HOST_FIRST_DEL_TMS DATE,
       FIRST_BA_DLV_TMS DATE,
       COMPLETE number(10,0),
       PRIMITIVE_ERROR varchar2(50),
       REJECT_REASON number(10,0),
       STATUS_INFO varchar2(1024),
       CSW_RETRY_CNT number(10,0),
       CSW_VERSION number(19,0),
       primary key (ID)
    )
/
       create table FMS_SEND_MQI (
       ID_SYNC_SEND number(19,0) not null,
       LOCALBA_ID varchar2(12) not null,
       REMOTEBA_ID varchar2(12) not null,
       STATUS varchar2(255),
       CSW_STATUS varchar2(255),
       SEND_TYPE number(10,0),
       CORRELATION_ID varchar2(30),
       VFN varchar2(32) not null,
       FSIZE number(19,0) not null,
       QUEUE_FILENAME varchar2(48) not null,
       GROUP_ID varchar2(48) not null,
       LINE_SEPARATOR varchar2(255) not null,
       RECORD_FORMAT varchar2(255),
       MAX_REC_LEN number(10,0),
       CHAR_TYPE varchar2(255) not null,
       ADF_LEN number(10,0),
       ADF varchar2(80),
       UDR_LEN number(10,0) not null,
       UDR varchar2(80) not null,
       TUR varchar2(16),
       MESSAGETYPE varchar2(3) not null,
       CATAPPL varchar2(4),
       LOCAL_BA_DATA varchar2(80),
       NET_FILE_SIZE number(19,0),
       TRANSFER_ID varchar2(16),
       FNAME varchar2(1024),
       FILE_DIGEST_ALG varchar2(8),
       FILE_DIGEST_LEN number(19,0),
       FILE_DIGEST varchar2(128),
       MSG_DIGEST_ALG varchar2(8),
       MSG_DIGEST_LEN number(19,0),
       MSG_DIGEST varchar2(128),
       MESSAGELEN number(10,0) not null,
       MESSAGE blob,
       LOCAL_AUTH_INFO_ALG varchar2(8),
       LOCAL_AUTH_INFO_LEN number(19,0),
       LOCAL_AUTH_INFO varchar2(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPTTIME DATE,
       START_CREATE_TIMESTAMP DATE,
       END_CREATE_TIMESTAMP DATE,
       ERROR_TIMESTAMP DATE,
       SENDTIME DATE,
       COMPLETETIME DATE,
       NOTIFYTIME DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       SEND_ERROR_TIMESTAMP DATE,
       COMPLETE number(10,0),
       PRIMITIVE_ERROR varchar2(50),
       REJECT_REASON number(10,0),
       STATUS_INFO varchar2(1024),
       NEG_DETAIL_OPER varchar2(1024),
       CSW_RETRY_CNT number(10,0),
       CSW_VERSION number(19,0),
       primary key (ID_SYNC_SEND)
    )
/
   create table FTS_RECV_MQI (
       ID number(19,0) not null,
       LOCALBA_ID varchar2(12) not null,
       REMOTEBA_ID varchar2(12) not null,
       STATUS varchar2(255),
       CSW_STATUS varchar2(255),
       CORRELATION_ID varchar2(30),
       VFN varchar2(32) not null,
       FSIZE number(19,0),
       QUEUE_FILENAME varchar2(48),
       GROUP_ID varchar2(48),
       LINE_SEPARATOR varchar2(255),
       RECORD_FORMAT varchar2(255),
       MAX_REC_LEN number(10,0),
       SND_CHAR_TYPE varchar2(255) not null,
       RCV_CHAR_TYPE varchar2(255),
       ADF_LEN number(10,0),
       ADF varchar2(80),
       TUR varchar2(16),
       LOCAL_BA_DATA varchar2(80),
       NET_FILE_SIZE number(19,0) not null,
       TRANSFER_ID varchar2(16) not null,
       FNAME varchar2(1024),
       FILE_DIGEST_ALG varchar2(8),
       FILE_DIGEST_LEN number(19,0),
       FILE_DIGEST varchar2(128),
       LOCAL_AUTH_INFO_ALG varchar2(8),
       LOCAL_AUTH_INFO_LEN number(19,0),
       LOCAL_AUTH_INFO varchar2(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPT_TMS DATE,
       START_READ_TMS DATE,
       END_READ_TMS DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       HOST_FIRST_SUB_TMS DATE,
       FER_SUB_TIME DATE,
       FEN_SUB_TMS DATE,
       HOST_FIRST_DEL_TMS DATE,
       FIRST_BA_DLV_TMS DATE,
       COMPLETE number(10,0),
       PRIMITIVE_ERROR varchar2(50),
       REJECT_REASON number(10,0),
       STATUS_INFO varchar2(1024),
       CSW_RETRY_CNT number(10,0),
       CSW_VERSION number(19,0),
       primary key (ID)
    )
/
    create table FTS_SEND_MQI (
       ID_SEND_FILE number(19,0) not null,
       LOCALBA_ID varchar2(12) not null,
       REMOTEBA_ID varchar2(12) not null,
       STATUS varchar2(255),
       CSW_STATUS varchar2(255),
       SEND_TYPE number(10,0),
       CORRELATION_ID varchar2(30),
       VFN varchar2(32) not null,
       FSIZE number(19,0) not null,
       QUEUE_FILENAME varchar2(48) not null,
       GROUP_ID varchar2(48) not null,
       LINE_SEPARATOR varchar2(255) not null,
       RECORD_FORMAT varchar2(255),
       MAX_REC_LEN number(10,0),
       CHAR_TYPE varchar2(255) not null,
       ADF_LEN number(10,0),
       ADF varchar2(80),
       MESSAGETYPE varchar2(3),
       LOCAL_BA_DATA varchar2(80),
       NET_FILE_SIZE number(19,0),
       TRANSFER_ID varchar2(16),
       FNAME varchar2(1024),
       FILE_DIGEST_ALG varchar2(8),
       FILE_DIGEST_LEN number(19,0),
       FILE_DIGEST varchar2(128),
       LOCAL_AUTH_INFO_ALG varchar2(8),
       LOCAL_AUTH_INFO_LEN number(19,0),
       LOCAL_AUTH_INFO varchar2(128),
       CSW_INSERT_TIMESTAMP DATE,
       ACCEPTTIME DATE,
       START_CREATE_TIMESTAMP DATE,
       END_CREATE_TIMESTAMP DATE,
       ERROR_TIMESTAMP DATE,
       SENDTIME DATE,
       COMPLETETIME DATE,
       NOTIFYTIME DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       SEND_ERROR_TIMESTAMP DATE,
       COMPLETE number(10,0),
       PRIMITIVE_ERROR varchar2(50),
       REJECT_REASON number(10,0),
       STATUS_INFO varchar2(1024),
       NEG_DETAIL_OPER varchar2(1024),
       CSW_RETRY_CNT number(10,0),
       CSW_VERSION number(19,0),
       primary key (ID_SEND_FILE)
    )
/
     create table MSS_RECV_MQI (
       ID number(19,0) not null,
       LOCALBA_ID varchar2(12) not null,
       REMOTEBA_ID varchar2(12) not null,
       STATUS varchar2(255),
       CSW_STATUS varchar2(255),
       MSGID varchar2(30) not null,
--       MSGIDR varchar2(30) not null,
       PRIORITY number(10,0) not null,
       UDR_LEN number(10,0),
       UDR varchar2(80),
       TUR varchar2(16),
       MESSAGETYPE varchar2(3) not null,
       CATAPPL varchar2(4),
       MSG_DIGEST_ALG varchar2(8),
       MSG_DIGEST_LEN number(19,0),
       MSG_DIGEST varchar2(128),
       MESSAGE blob,
       LOCAL_AUTH_INFO_ALG varchar2(8),
       LOCAL_AUTH_INFO_LEN number(19,0),
       LOCAL_AUTH_INFO varchar2(128),
       CSW_INSERT_TIMESTAMP DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       HOST_FIRST_SUB_TMS DATE,
       FER_SUB_TIME DATE,
       FEN_SUB_TMS DATE,
       HOST_FIRST_DEL_TMS DATE,
       FIRST_BA_DLV_TMS DATE,
       COMPLETE number(10,0),
       PRIMITIVE_ERROR varchar2(50),
       REJECT_REASON number(10,0),
       STATUS_INFO varchar2(1024),
       CSW_RETRY_CNT number(10,0),
       CSW_VERSION number(19,0),
       primary key (ID)
    )
/
    create table MSS_SEND_MQI (
       FAS_SEQID number(19,0) not null,
       LOCALBA_ID varchar2(12) not null,
       REMOTEBA_ID varchar2(12) not null,
       STATUS varchar2(255),
       CSW_STATUS varchar2(255),
       LOCAL_BA_DATA varchar2(100),
--       MSGID varchar2(30) not null,
       PRIORITY number(10,0) not null,
       TUR varchar2(16),
       MSG_TYPE varchar2(3) not null,
       CAT_APPL varchar2(4),
       CORRELATION_ID varchar2(30),
       UDR_LEN number(10,0),
       UDR varchar2(80),
       MSG_DIGEST_ALG varchar2(8),
       MSG_DIGEST_LEN number(19,0),
       MSG_DIGEST varchar2(128),
       MESSAGELEN number(10,0) not null,
       MESSAGE blob,
       LOCAL_AUTH_INFO_ALG varchar2(8),
       LOCAL_AUTH_INFO_LEN number(19,0),
       LOCAL_AUTH_INFO varchar2(128),
       CSW_INSERT_TIMESTAMP DATE,
       BA_REQ_TMS DATE,
       ACCEPTTIME DATE,
       SENDTIME DATE,
       COMPLETETIME DATE,
       NOTIFYTIME DATE,
       BA_PROCESS_TMS DATE,
       CSW_PROCESS_TMS DATE,
       SEND_ERROR_TIMESTAMP DATE,
       COMPLETE number(10,0),
       PRIMITIVE_ERROR varchar2(50),
       REJECT_REASON number(10,0),
       STATUS_INFO varchar2(1024),
       CSW_RETRY_CNT number(10,0),
       CSW_VERSION number(19,0),
       primary key (FAS_SEQID)
    )
/
create sequence SYNC_SEND_SEQ_MQ start with 1 increment by  1
/
create sequence SYNC_RECV_SEQ_MQ start with 1 increment by  1
/
create sequence SEND_FILE_SEQ_MQ start with 1 increment by  1
/
create sequence RECV_FILE_SEQ_MQ start with 1 increment by  1
/
create sequence FAS_MSG_SEND_SEQ_MQ start with 1 increment by  1
/
create sequence FAS_MSG_RECV_SEQ_MQ start with 1 increment by  1
/
