ALTER TABLE USERS ADD SECRET_ANSWER_ONE VARCHAR2(255)
/
ALTER TABLE USERS ADD SECRET_ANSWER_TWO VARCHAR2(255)
/
ALTER TABLE USERS ADD SECRET_RESPONSE_ONE VARCHAR2(255)
/
ALTER TABLE USERS ADD SECRET_RESPONSE_TWO VARCHAR2(255)
/