ALTER TABLE CONFIGURATION_FMS_LOCALBA_REMOTEBA MODIFY "LAU_ENABLED" DEFAULT 0
/
ALTER TABLE CONFIGURATION_FTS_LOCALBA_REMOTEBA MODIFY "LAU_ENABLED" DEFAULT 0
/
ALTER TABLE CONFIGURATION_MSS_LOCALBA_REMOTEBA MODIFY "LAU_ENABLED" DEFAULT 0
/