ALTER TABLE ADD_ON_CONFIGURATION_FTS DROP CONSTRAINT RCV_PATH_CONSTRAIN
/
ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA MODIFY ("LOCALBAID" NULL)
/
ALTER TABLE CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA MODIFY ("REMOTEBAID" NULL)
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA MODIFY ("LOCALBAID" NULL)
/
ALTER TABLE CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA MODIFY ("REMOTEBAID" NULL)
/
ALTER TABLE CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA MODIFY ("LOCALBAID" NULL)
/
ALTER TABLE CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA MODIFY ("REMOTEBAID" NULL)
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID)
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID)
/
alter table CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA add constraint UNIQUE_CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID)
/
