<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.cbi.chc.csw</groupId>
		<artifactId>chc-ccr-clientsw</artifactId>
		<version>1.10.0</version>
	</parent>
	<artifactId>chc-ccr-clientsw-service</artifactId>

	<dependencies>
	<!-- framework dependencies -->
		<dependency>
			<groupId>com.cbi.chc.framework</groupId>
			<artifactId>chc-framework-micros</artifactId>
			<version>${chc-framework-version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.framework</groupId>
			<artifactId>chc-framework-util</artifactId>
			<version>${chc-framework-version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.framework</groupId>
			<artifactId>chc-framework-http</artifactId>
			<version>${chc-framework-version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.framework</groupId>
			<artifactId>chc-framework-internal-dto</artifactId>
			<version>${chc-framework-version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.framework</groupId>
			<artifactId>chc-framework-encryption</artifactId>
			<version>${chc-framework-version}</version>
		</dependency>
		
		<!-- CCR dependencies -->
		<dependency>
			<groupId>com.cbi.chc.ccr</groupId>
			<artifactId>chc-ccr-clientsw-dto</artifactId>
			<version>${chc-ccr-version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-encryption</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-domain</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-mq-domain</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>oauth2-oidc-sdk</artifactId>
			<version>9.37.2</version>
		</dependency>
		<dependency>
    		<groupId>commons-codec</groupId>
    		<artifactId>commons-codec</artifactId>
		</dependency>

		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpg-jdk15on</artifactId>
		</dependency>
		
	</dependencies>
</project>