-- Ricerca batch falliti per abbandono o riavvio
SELECT B.JOB_NAME, A.JOB_EXECUTION_ID, A.JOB_INSTANCE_ID, A.CREATE_TIME, A.START_TIME, A.END_TIME, A.STATUS, A.EXIT_CODE, A.LAST_UPDATED 
FROM DB2C.IQCB3_JOB_EXECUTION A INNER JOIN db2c.IQCB3_JOB_INSTANCE B ON A.JOB_INSTANCE_ID = B.JOB_INSTANCE_ID
WHERE STATUS NOT IN ('COMPLETED', 'ABANDONED') ORDER BY 3 DESC


-- Richerca BATCH
SELECT * FROM DB2C.IQCB3_JOB_EXECUTION ije WHERE JOB_INSTANCE_ID = 'XXXXXXXXX';

-- Verifica STEP
SELECT * FROM DB2C.IQCB3_STEP_EXECUTION ise WHERE JOB_EXECUTION_ID = 'XXXXXXXXX';

-- QUERY PER VERFICARE QUANTI SUPPORTI INFORMATIVI SONO IN STATO I_001 E QUANTI IN A_001 (UNLOAD) --ATTENZIONE in IQC01_JOB_EXECUTION_ID va messo il job instance id
SELECT COUNT(IQCI01_ID_DIST), IQCI01_STATO FROM DB2C.IQCI01_TB_FLUSSO_IDX itfi WHERE IQCI01_JOB_EXECUTION_ID = 'XXXXXXXXX' GROUP BY IQCI01_STATO ; 
--INSERIRE IL JOB_INSTANCE INVECE DEL JOB_EXECUTION

-- QUERY PER VERFICARE QUANTI SUPPORTI DISPOSITIVI SONO IN STATO I_001 E QUANTI IN A_001 (UNLOAD)
SELECT COUNT(IQCD01_ID_DIST), IQCD01_STATO FROM DB2C.IQCD01_TB_FLUSSO_IDX itfi WHERE IQCD01_JOB_EXECUTION_ID = 'XXXXXXXXX' GROUP BY IQCD01_STATO ; 
--INSERIRE IL JOB_INSTANCE INVECE DEL JOB_EXECUTION

-- Verifica esecuzione batch dopo riavvio da cartone
SELECT B.JOB_NAME, A.JOB_EXECUTION_ID, A.JOB_INSTANCE_ID, A.CREATE_TIME, A.START_TIME, A.END_TIME, A.STATUS, A.EXIT_CODE, A.LAST_UPDATED 
FROM DB2C.IQCB3_JOB_EXECUTION A INNER JOIN db2c.IQCB3_JOB_INSTANCE B ON A.JOB_INSTANCE_ID = B.JOB_INSTANCE_ID
WHERE JOB_NAME LIKE 'XXX_NOME_BATCH_XXX' ORDER BY START_TIME DESC;

UPDATE DB2C.IQCD01_TB_FLUSSO_IDX itfi SET IQCD01_STATO = 'I_001', IQCD01_JOB_EXECUTION_ID = 0 WHERE IQCD01_JOB_EXECUTION_ID = '' AND IQCD01_STATO = 'I_001';

