server.port=40001
spring.application.name=clientsw-all

csw.ssl.enabled=false
csw.ssl.keyAlias=springboot
csw.ssl.keyStorePassword=changeit
csw.ssl.keyStore=keystore/clientkey.jks


#logging.level.org.springframework=DEBUG
logging.level.com.cbi.frw=INFO
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=trace 
#logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
#poller invio primitive
logging.level.com.cbi.ccr.csw.poller.mq.service=DEBUG

logging.level.com.cbi.ccr.csw.femws=DEBUG
logging.file.max-size=5MB
logging.file.total-size-cap=10MB
logging.file.max-history=50
logging.file.clean-history-on-start=true

logging.file.name=${LOG_FILE:/tmp/chc/csw_default.log}
#logging.pattern.console="%d %-5level %logger : %msg%n"
logging.pattern.file="%d %-5level [%thread] %logger : %msg%n"


springdoc.swagger-ui.enabled=false

spring.profiles.active=DASHBOARD,POLLER,BATCH_OUTBOUND_WORKER,BATCH_INBOUND_WORKER,SOAP_OUTBOUND_FACADE,SOAP_INBOUND_WORKER,REST_OUTBOUND_FACADE
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

#maximum number of milliseconds that a client will wait for a connection
spring.datasource.hikari.connection-timeout=30000
#minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.minimum-idle=5
#maximum pool size
spring.datasource.hikari.maximum-pool-size=15
#maximum idle time for connection
spring.datasource.hikari.idle-timeout=10000
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
spring.datasource.hikari.max-lifetime=30000

# Cybrark VAULT section
vault.enabled=false
# comma separated values, eg: postgres,postgres1
vault.databaseUser=
# eg. Safe=xyz;Folder=Root;Object=xyzB
vault.query=
vault.appID=MyID


client_id=CSW-1
client_group_id=GRP-1
client_hostname=localhost
csw_version=1.0

# Proxy server configuration for outgoing http calls
proxy_host=
proxy_port=
proxy_user=
proxy_password=

#spring.output.ansi.enabled=ALWAYS
#spring.output.ansi.enabled=NEVER
spring.output.ansi.enabled=DETECT


# use to simulate error and test cases conditions
integration_test_active=false

max_retry_attempts=2

# update the service status every X milliseconds (interval)  
csw_service_status_update_interval=5000

local_temp_folder_encrypted=/tmp/chc/csw/outbound/encrypted
conversion-folder=/tmp/chc/csw/outbound/conversion

# connection timeout while sending to CCR in milliseconds
# se modifichi questo, allora modifica anche handleReadTimeout nel CCR TEST-SIMULATION CCRInboundFMSController
ccr_http_timeout=10000
ccr_host_batch=http://localhost:50001
#zuul  INT
#ccr_host_batch=http://10.1.32.52:4000
# diretto CCr INT
#ccr_host_batch=http://10.1.32.62:50001


## CSW 6 sia lab
#client-software-id=0bce2aea-c08f-4e14-af50-db9ee37817db
## CSW 1 sia lab

#api-gateway-public-key-url=https://intapi.nexi.it/openid/connect/jwks.json
api-gateway-public-key-url=https://intapi.nexi.it/chc/ccr/jwks.json
nexi-oauth-token-url=https://intapi.nexi.it/b2b/chc/oauth/ccr/token
#nexi-oauth-token-url=http://localhost:60005/chc/oauth/ccr/token

#SECURITY
client-software-id=dbd3f868-84c9-48ea-b789-eeb7a04d246a
csw_local_encryption_key=0123456789ABCDEF0123456789ABCDEF
enable-security=true
enable_encryption=true
csw_issued_at_seconds_to_remove=10
csw_not_before_seconds_to_remove=120

# da internet   
#crypto_hub_url=https://intapi.nexi.it/b2b/chc/cryptohub/getkey
# da VPN Nexi   
#crypto_hub_url=https://intapi.nexi.local:8443/b2b/chc/cryptohub/getkey
#Local
crypto_hub_url=http://localhost:40001/chc/b2b/cryptohub/getkey
#crypto_hub_url=http://localhost:60005/chc-cryptohub/rest/getkey



######### INBOUND
spring.servlet.multipart.max-file-size=4GB
spring.servlet.multipart.max-request-size=4GB
spring.servlet.multipart.location=/tmp/chc/csw/inbound/encrypted
local_storage_path_encrypted=/tmp/chc/csw/inbound/encrypted
local_storage_path_decrypted=/tmp/chc/csw/inbound/decrypted
######### INBOUND END

########### POLLER
fixed_poller_delay=10000
fixed_mq_poller_delay=5000
# numero di thread da attivare per ogni worker
outbound_worker_threads=1
## invio multi thread verso uno o piu' worker. Potrebeb anche essere sempre ,o stesso
outbound_workers[0]=http://localhost:40001
########### POLLER END

########### Restful
rest_traceBody=true

#orchestrator_restful_endpoint=http://localhost:60005/orchestrator/simulator/restful
orchestrator_restful_endpoint=https://intapi.nexi.it/b2b/chc
########### Restful END

########### SOAP 
femswsName=Client-SW
femsWsId=ClienmSW-1
fengId=feng_Id
# Recupero header dalla request per chiamate con porta di dominio (PDD)
femswsHeaderHandler=false
traceBody=true
# dimensione massima in MB accettata per i messaggi SOAP
maxMessageSizeAllowed=1
#ccr_host_online=https://intapi.nexi.it/b2b/chc
ccr_host_online=http://localhost:50001
########### SOAP END

########### DASHBOARD
jwt_secret=jwtsecret
jwt_expiration=3000
jwt_refresh_expiration=180000

outbound_mq_datefilter_column=cswInsertTimestamp
inbound_mq_datefilter_column=cswInsertTimestamp

outbound_db_datefilter_column=baInsertTimestamp

fms_inbound_db_datefilter_column=receiveTimestamp
# fts_inbound_db_datefilter_column=createDate
fts_inbound_db_datefilter_column=receiveTimestamp
mss_inbound_db_datefilter_column=receiveTimestamp

status_column=status
status_ba_column=status
########### DASHBOARD END

# per MQ
enable_debug_primitive_mq=true


# numero di thread per listenere MQ can be 1-5 or 5 or more
outbound_mq_listener_concurrency=5
local_temp_folder_file_mq=/tmp/chc/csw/outbound/mq


