create sequence SEQ_CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA start with 1 increment by 1;
create sequence SEQ_CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA start with 1 increment by 1;
create sequence SEQ_CONFIGURATION_MQ_PRIMITIVE start with 1 increment by 1;
create sequence SEQ_CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA start with 1 increment by 1;
create sequence SEQ_FMS_SEND_MQI start with 1 increment by 1;
create sequence SEQ_FTS_SEND_MQI start with 1 increment by 1;
create sequence SEQ_MSS_SEND_MQI start with 1 increment by 1;

    create table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA (
       id bigint not null,
        LOCALBAID varchar(12) not null,
        REMOTEBAID varchar(12) not null,
        INTERFACE_TYPE varchar(255) not null,
        LAU_ENABLED bit,
        LAU_KEY varchar(255),
        RCV_COMPLETION_ALGO bit,
        SND_COMPLETION_ALGO bit,
        HUB_CODE_PAGE varchar(255),
        HUB_LINE_SEPARATOR varchar(255),
        RCV_CODE_PAGE varchar(255),
        RCV_LINE_SEPARATOR varchar(255),
        RCV_MAX_REC_LENGHT int,
        RCV_PATH varchar(255),
        RCV_RECORD_FORMAT varchar(255),
        SND_CODE_PAGE varchar(255),
        SND_LINE_SEPARATOR varchar(255),
        SND_MAX_REC_LENGHT int,
        SND_RECORD_FORMAT varchar(255),
        MQI_POS_CREATE_IND bit,
        RCV_AUTO_READ bit,
        RCV_PRIM_CONV_FORMAT varchar(255),
        UPLOAD_Q_NAME varchar(255),
        primary key (id)
    );

    create table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA (
       id bigint not null,
        LOCALBAID varchar(12) not null,
        REMOTEBAID varchar(12) not null,
        INTERFACE_TYPE varchar(255) not null,
        LAU_ENABLED bit,
        LAU_KEY varchar(255),
        RCV_COMPLETION_ALGO bit,
        SND_COMPLETION_ALGO bit,
        HUB_CODE_PAGE varchar(255),
        HUB_LINE_SEPARATOR varchar(255),
        RCV_CODE_PAGE varchar(255),
        RCV_LINE_SEPARATOR varchar(255),
        RCV_MAX_REC_LENGHT int,
        RCV_PATH varchar(255),
        RCV_RECORD_FORMAT varchar(255),
        SND_CODE_PAGE varchar(255),
        SND_LINE_SEPARATOR varchar(255),
        SND_MAX_REC_LENGHT int,
        SND_RECORD_FORMAT varchar(255),
        MQI_POS_CREATE_IND bit,
        RCV_AUTO_READ bit,
        RCV_PRIM_CONV_FORMAT varchar(255),
        UPLOAD_Q_NAME varchar(255),
        primary key (id)
    );

    create table CONFIGURATION_MQ_PRIMITIVE (
       id bigint not null,
        MQ_CHANNEL varchar(255),
        PRIMITIVE varchar(255),
        QUEUE_NAME varchar(255),
        TO_LOAD bit,
        primary key (id)
    );

    create table CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA (
       id bigint not null,
        LOCALBAID varchar(12) not null,
        REMOTEBAID varchar(12) not null,
        INTERFACE_TYPE varchar(255) not null,
        LAU_ENABLED bit,
        LAU_KEY varchar(255),
        RCV_COMPLETION_ALGO bit,
        SND_COMPLETION_ALGO bit,
        RCV_PRIM_CONV_FORMAT varchar(255),
        primary key (id)
    );

    create table FMS_RECV_MQI (
       ID bigint not null,
        MESSAGE varbinary(MAX),
        ACCEPT_TMS datetime2,
        ADF varchar(80),
        ADF_LEN int,
        BA_PROCESS_TMS datetime2,
        CATAPPL varchar(4),
        COMPLETE int,
        CORRELATION_ID varchar(30),
        CSW_INSERT_TIMESTAMP datetime2,
        CSW_PROCESS_TMS datetime2,
        CSW_STATUS varchar(60),
        END_READ_TMS datetime2,
        FEN_SUB_TMS datetime2,
        FER_SUB_TIME datetime2,
        FILE_DIGEST varchar(128),
        FILE_DIGEST_ALG varchar(8),
        FILE_DIGEST_LEN bigint,
        FNAME varchar(1024),
        FSIZE bigint not null,
        FIRST_BA_DLV_TMS datetime2,
        GROUP_ID varchar(48),
        HOST_FIRST_DEL_TMS datetime2,
        HOST_FIRST_SUB_TMS datetime2,
        LINE_SEPARATOR varchar(255),
        LOCAL_AUTH_INFO varchar(128),
        LOCAL_AUTH_INFO_ALG varchar(8),
        LOCAL_AUTH_INFO_LEN bigint,
        LOCAL_BA_DATA varchar(80),
        LOCALBA_ID varchar(12) not null,
        MAX_REC_LEN int,
        MESSAGELEN int not null,
        MESSAGETYPE varchar(3) not null,
        MSG_DIGEST varchar(128),
        MSG_DIGEST_ALG varchar(8),
        MSG_DIGEST_LEN bigint,
        NET_FILE_SIZE bigint,
        PRIMITIVE_ERROR varchar(50),
        QUEUE_FILENAME varchar(48),
        RCV_CHAR_TYPE varchar(255),
        RECORD_FORMAT varchar(255),
        REJECT_REASON int,
        REMOTEBA_ID varchar(12) not null,
        CSW_RETRY_CNT int,
        SND_CHAR_TYPE varchar(255) not null,
        START_READ_TMS datetime2,
        STATUS varchar(255),
        STATUS_INFO varchar(1024),
        TRANSFER_ID varchar(16) not null,
        TUR varchar(16),
        UDR varchar(80) not null,
        UDR_LEN int not null,
        CSW_VERSION bigint,
        VFN varchar(32) not null,
        primary key (ID)
    );

    create table FMS_SEND_MQI (
       ID_SYNC_SEND bigint not null,
        MESSAGE varbinary(MAX),
        ACCEPTTIME datetime2,
        ADF varchar(80),
        ADF_LEN int,
        BA_PROCESS_TMS datetime2,
        CATAPPL varchar(4),
        CHAR_TYPE varchar(255) not null,
        COMPLETE int,
        COMPLETETIME datetime2,
        CORRELATION_ID varchar(30),
        CSW_INSERT_TIMESTAMP datetime2,
        CSW_PROCESS_TMS datetime2,
        CSW_STATUS varchar(60),
        END_CREATE_TIMESTAMP datetime2,
        ERROR_TIMESTAMP datetime2,
        FILE_DIGEST varchar(128),
        FILE_DIGEST_ALG varchar(8),
        FILE_DIGEST_LEN bigint,
        FNAME varchar(1024),
        FSIZE bigint not null,
        GROUP_ID varchar(48) not null,
        LINE_SEPARATOR varchar(255) not null,
        LOCAL_AUTH_INFO varchar(128),
        LOCAL_AUTH_INFO_ALG varchar(8),
        LOCAL_AUTH_INFO_LEN bigint,
        LOCAL_BA_DATA varchar(80),
        LOCALBA_ID varchar(12) not null,
        MAX_REC_LEN int,
        MESSAGELEN int not null,
        MESSAGETYPE varchar(3) not null,
        MSG_DIGEST varchar(128),
        MSG_DIGEST_ALG varchar(8),
        MSG_DIGEST_LEN bigint,
        NEG_DETAIL_OPER varchar(1024),
        NET_FILE_SIZE bigint,
        NOTIFYTIME datetime2,
        CSW_PRIMITIVE varchar(20),
        PRIMITIVE_ERROR varchar(50),
        QUEUE_FILENAME varchar(48) not null,
        RECORD_FORMAT varchar(255),
        REJECT_REASON int,
        REMOTEBA_ID varchar(12) not null,
        CSW_RETRY_CNT int,
        SEND_ERROR_TIMESTAMP datetime2,
        SENDTIME datetime2,
        SEND_TYPE int,
        START_CREATE_TIMESTAMP datetime2,
        STATUS varchar(255),
        STATUS_INFO varchar(1024),
        TRANSFER_ID varchar(16),
        TUR varchar(16),
        UDR varchar(80) not null,
        UDR_LEN int not null,
        CSW_VERSION bigint,
        VFN varchar(32) not null,
        primary key (ID_SYNC_SEND)
    );

    create table FTS_RECV_MQI (
       ID bigint not null,
        ACCEPT_TMS datetime2,
        ADF varchar(80),
        ADF_LEN int,
        BA_PROCESS_TMS datetime2,
        COMPLETE int,
        CORRELATION_ID varchar(30),
        CSW_INSERT_TIMESTAMP datetime2,
        CSW_PROCESS_TMS datetime2,
        CSW_STATUS varchar(60),
        END_READ_TMS datetime2,
        FEN_SUB_TMS datetime2,
        FER_SUB_TIME datetime2,
        FILE_DIGEST varchar(128),
        FILE_DIGEST_ALG varchar(8),
        FILE_DIGEST_LEN bigint,
        FNAME varchar(1024),
        FSIZE bigint,
        FIRST_BA_DLV_TMS datetime2,
        GROUP_ID varchar(48),
        HOST_FIRST_DEL_TMS datetime2,
        HOST_FIRST_SUB_TMS datetime2,
        LINE_SEPARATOR varchar(255),
        LOCAL_AUTH_INFO varchar(128),
        LOCAL_AUTH_INFO_ALG varchar(8),
        LOCAL_AUTH_INFO_LEN bigint,
        LOCAL_BA_DATA varchar(80),
        LOCALBA_ID varchar(12) not null,
        MAX_REC_LEN int,
        NET_FILE_SIZE bigint not null,
        PRIMITIVE_ERROR varchar(50),
        QUEUE_FILENAME varchar(48),
        RCV_CHAR_TYPE varchar(255),
        RECORD_FORMAT varchar(255),
        REJECT_REASON int,
        REMOTEBA_ID varchar(12) not null,
        CSW_RETRY_CNT int,
        SND_CHAR_TYPE varchar(255) not null,
        START_READ_TMS datetime2,
        STATUS varchar(255),
        STATUS_INFO varchar(1024),
        TRANSFER_ID varchar(16) not null,
        TUR varchar(16),
        CSW_VERSION bigint,
        VFN varchar(32) not null,
        primary key (ID)
    );

    create table FTS_SEND_MQI (
       ID_SEND_FILE bigint not null,
        ACCEPTTIME datetime2,
        ADF varchar(80),
        ADF_LEN int,
        BA_PROCESS_TMS datetime2,
        CHAR_TYPE varchar(255) not null,
        COMPLETE int,
        COMPLETETIME datetime2,
        CORRELATION_ID varchar(30),
        CSW_INSERT_TIMESTAMP datetime2,
        CSW_PROCESS_TMS datetime2,
        CSW_STATUS varchar(60),
        END_CREATE_TIMESTAMP datetime2,
        ERROR_TIMESTAMP datetime2,
        FILE_DIGEST varchar(128),
        FILE_DIGEST_ALG varchar(8),
        FILE_DIGEST_LEN bigint,
        FNAME varchar(1024),
        FSIZE bigint not null,
        GROUP_ID varchar(48) not null,
        LINE_SEPARATOR varchar(255) not null,
        LOCAL_AUTH_INFO varchar(128),
        LOCAL_AUTH_INFO_ALG varchar(8),
        LOCAL_AUTH_INFO_LEN bigint,
        LOCAL_BA_DATA varchar(80),
        LOCALBA_ID varchar(12) not null,
        MAX_REC_LEN int,
        MESSAGETYPE varchar(3),
        NEG_DETAIL_OPER varchar(1024),
        NET_FILE_SIZE bigint,
        NOTIFYTIME datetime2,
        CSW_PRIMITIVE varchar(20),
        PRIMITIVE_ERROR varchar(50),
        QUEUE_FILENAME varchar(48) not null,
        RECORD_FORMAT varchar(255),
        REJECT_REASON int,
        REMOTEBA_ID varchar(12) not null,
        CSW_RETRY_CNT int,
        SEND_ERROR_TIMESTAMP datetime2,
        SENDTIME datetime2,
        SEND_TYPE int,
        START_CREATE_TIMESTAMP datetime2,
        STATUS varchar(255),
        STATUS_INFO varchar(1024),
        TRANSFER_ID varchar(16),
        CSW_VERSION bigint,
        VFN varchar(32) not null,
        primary key (ID_SEND_FILE)
    );

    create table MSS_RECV_MQI (
       ID bigint not null,
        MESSAGE varbinary(MAX),
        BA_PROCESS_TMS datetime2,
        CATAPPL varchar(4),
        COMPLETE int,
        CSW_INSERT_TIMESTAMP datetime2,
        CSW_PROCESS_TMS datetime2,
        CSW_STATUS varchar(60),
        FEN_SUB_TMS datetime2,
        FER_SUB_TIME datetime2,
        FIRST_BA_DLV_TMS datetime2,
        HOST_FIRST_DEL_TMS datetime2,
        HOST_FIRST_SUB_TMS datetime2,
        LOCAL_AUTH_INFO varchar(128),
        LOCAL_AUTH_INFO_ALG varchar(8),
        LOCAL_AUTH_INFO_LEN bigint,
        LOCALBA_ID varchar(12) not null,
        MESSAGETYPE varchar(3) not null,
        MSG_DIGEST varchar(128),
        MSG_DIGEST_ALG varchar(8),
        MSG_DIGEST_LEN bigint,
        MSGID varchar(30) not null,
        PRIMITIVE_ERROR varchar(50),
        PRIORITY int not null,
        REJECT_REASON int,
        REMOTEBA_ID varchar(12) not null,
        CSW_RETRY_CNT int,
        STATUS varchar(255),
        STATUS_INFO varchar(1024),
        TUR varchar(16),
        UDR varchar(80),
        UDR_LEN int,
        CSW_VERSION bigint,
        primary key (ID)
    );

    create table MSS_SEND_MQI (
       FAS_SEQID bigint not null,
        MESSAGE varbinary(MAX),
        ACCEPTTIME datetime2,
        BA_PROCESS_TMS datetime2,
        BA_REQ_TMS datetime2,
        CAT_APPL varchar(4),
        COMPLETE int,
        COMPLETETIME datetime2,
        CORRELATION_ID varchar(30),
        CSW_INSERT_TIMESTAMP datetime2,
        CSW_PROCESS_TMS datetime2,
        CSW_STATUS varchar(60),
        SEND_ERROR_TIMESTAMP datetime2,
        LOCAL_AUTH_INFO varchar(128),
        LOCAL_AUTH_INFO_ALG varchar(8),
        LOCAL_AUTH_INFO_LEN bigint,
        LOCAL_BA_DATA varchar(100),
        LOCALBA_ID varchar(12) not null,
        MESSAGELEN int not null,
        MSG_TYPE varchar(3) not null,
        MSG_DIGEST varchar(128),
        MSG_DIGEST_ALG varchar(8),
        MSG_DIGEST_LEN bigint,
        NOTIFYTIME datetime2,
        CSW_PRIMITIVE varchar(20),
        PRIMITIVE_ERROR varchar(50),
        PRIORITY int not null,
        REJECT_REASON int,
        REMOTEBA_ID varchar(12) not null,
        CSW_RETRY_CNT int,
        SENDTIME datetime2,
        STATUS varchar(255),
        STATUS_INFO varchar(1024),
        TUR varchar(16),
        UDR varchar(80),
        UDR_LEN int,
        CSW_VERSION bigint,
        primary key (FAS_SEQID)
    );

    alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA 
       add constraint UNIQUE_CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID);

    alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA 
       add constraint UNIQUE_CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID);

    alter table CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA 
       add constraint UNIQUE_CONFIGURATION_MSS_MQ_LOCALBA_REMOTEBA unique (INTERFACE_TYPE, LOCALBAID, REMOTEBAID);
