
    create table BA_URL (
       id number(19,0) not null,
        active number(1,0),
        BA_ID varchar2(255 char),
        URL varchar2(255 char),
        primary key (id)
    );

    create table ccr_fms_message (
       phy_msg_id number(19,0) not null,
        BA_INSERT_TIMESTAMP timestamp,
        CHC_ID number(19,0),
        client_sw_msg_id number(19,0),
        direction varchar2(10 char),
        insert_Date timestamp,
        local_auth_info varchar2(128 char),
        local_auth_info_alg varchar2(8 char),
        LOCALBA_ID varchar2(12 char),
        log varchar2(1024 char),
        REMOTE_BA_ID varchar2(12 char),
        status varchar2(255 char),
        sub_status varchar2(255 char),
        cat_appl varchar2(4 char),
        CODE_PAGE varchar2(255 char),
        file_digest varchar2(128 char),
        file_digest_alg varchar2(8 char),
        file_hash varchar2(32 char),
        file_name varchar2(1024 char),
        file_size number(19,0),
        FTSDELIVTIME timestamp,
        LINE_SEPARATOR varchar2(255 char),
        MAX_RECORD_LENGTH number(10,0),
        message_leng number(10,0),
        message_type varchar2(3 char),
        message_digest varchar2(128 char),
        message_digest_alg varchar2(8 char),
        RECORD_FORMAT varchar2(255 char),
        repo_file_id varchar2(50 char),
        repo_message_id varchar2(50 char),
        tur varchar2(16 char),
        udr varchar2(80 char),
        vfn varchar2(32 char),
        primary key (phy_msg_id)
    );

    create table ccr_fts_message (
       phy_msg_id number(19,0) not null,
        BA_INSERT_TIMESTAMP timestamp,
        CHC_ID number(19,0),
        client_sw_msg_id number(19,0),
        direction varchar2(10 char),
        insert_Date timestamp,
        local_auth_info varchar2(128 char),
        local_auth_info_alg varchar2(8 char),
        LOCALBA_ID varchar2(12 char),
        log varchar2(1024 char),
        REMOTE_BA_ID varchar2(12 char),
        status varchar2(255 char),
        sub_status varchar2(255 char),
        APPLICATIVE_DATA_FIELD varchar2(80 char),
        CODE_PAGE varchar2(255 char),
        FSIZE number(19,0),
        FILE_DIGEST varchar2(128 char),
        FILE_DIGEST_ALG varchar2(8 char),
        FNAME varchar2(1024 char),
        FMD5 varchar2(32 char),
        LINE_SEPARATOR varchar2(255 char),
        MAX_RECORD_LENGTH number(10,0),
        RECORD_FORMAT varchar2(255 char),
        VFN varchar2(32 char),
        primary key (phy_msg_id)
    );

    create table ccr_mss_message (
       phy_msg_id number(19,0) not null,
        BA_INSERT_TIMESTAMP timestamp,
        CHC_ID number(19,0),
        client_sw_msg_id number(19,0),
        direction varchar2(10 char),
        insert_Date timestamp,
        local_auth_info varchar2(128 char),
        local_auth_info_alg varchar2(8 char),
        LOCALBA_ID varchar2(12 char),
        log varchar2(1024 char),
        REMOTE_BA_ID varchar2(12 char),
        status varchar2(255 char),
        sub_status varchar2(255 char),
        CAT_APPL varchar2(4 char),
        MAB blob,
        MSG_TYPE varchar2(3 char),
        MSG_DIGEST varchar2(128 char),
        MSG_DIGEST_ALG varchar2(8 char),
        MSGSIZE number(10,0),
        PRIORITY number(10,0),
        REMOTE_REF varchar2(80 char),
        TUR varchar2(16 char),
        primary key (phy_msg_id)
    );
