update CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA SET SND_CODE_PAGE = 'BINARY' where SND_CODE_PAGE is NULL
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA add constraint df_SND_CODE_PAGE DEFAULT 'BINARY' for SND_CODE_PAGE
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA alter column SND_CODE_PAGE varchar(255) NOT NULL
/

update CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA SET SND_LINE_SEPARATOR = 'NONE' where SND_LINE_SEPARATOR is NULL
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA add constraint df_SND_LINE_SEPARATOR DEFAULT 'NONE' for SND_LINE_SEPARATOR
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA alter column SND_LINE_SEPARATOR varchar(255) NOT NULL
/

update CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA SET SND_RECORD_FORMAT = 'VARIABLE' where SND_RECORD_FORMAT is NULL
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA add constraint df_SND_RECORD_FORMAT DEFAULT 'VARIABLE' for SND_RECORD_FORMAT
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA alter column SND_RECORD_FORMAT varchar(255) NOT NULL
/

update CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA SET SND_CODE_PAGE = 'BINARY' where SND_CODE_PAGE is NULL
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA add constraint df1_SND_CODE_PAGE DEFAULT 'BINARY' for SND_CODE_PAGE
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA alter column SND_CODE_PAGE varchar(255) NOT NULL
/

update CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA SET SND_LINE_SEPARATOR = 'NONE' where SND_LINE_SEPARATOR is NULL
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA add constraint df1_SND_LINE_SEPARATOR DEFAULT 'NONE' for SND_LINE_SEPARATOR
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA alter column SND_LINE_SEPARATOR varchar(255) NOT NULL
/

update CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA SET SND_RECORD_FORMAT = 'VARIABLE' where SND_RECORD_FORMAT is NULL
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA add constraint df1_SND_RECORD_FORMAT DEFAULT 'VARIABLE' for SND_RECORD_FORMAT
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA alter column SND_RECORD_FORMAT varchar(255) NOT NULL
/
