update CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA SET SND_CODE_PAGE = 'BINARY' where SND_CODE_PAGE is NULL
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA MODIFY SND_CODE_PAGE varchar(255) DEFAULT 'BINARY' NOT NULL
/
update CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA SET SND_LINE_SEPARATOR = 'NONE' where SND_LINE_SEPARATOR is NULL
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA MODIFY SND_LINE_SEPARATOR varchar(255) DEFAULT 'NONE' NOT NULL
/
update CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA SET SND_RECORD_FORMAT = 'VARIABLE' where SND_RECORD_FORMAT is NULL
/
alter table CONFIGURATION_FMS_MQ_LOCALBA_REMOTEBA MODIFY SND_RECORD_FORMAT varchar(255) DEFAULT 'VARIABLE' NOT NULL
/

update CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA SET SND_CODE_PAGE = 'BINARY' where SND_CODE_PAGE is NULL
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA MODIFY SND_CODE_PAGE varchar(255) DEFAULT 'BINARY' NOT NULL
/
update CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA SET SND_LINE_SEPARATOR = 'NONE' where SND_LINE_SEPARATOR is NULL
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA MODIFY SND_LINE_SEPARATOR varchar(255) DEFAULT 'NONE' NOT NULL
/
update CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA SET SND_RECORD_FORMAT = 'VARIABLE' where SND_RECORD_FORMAT is NULL
/
alter table CONFIGURATION_FTS_MQ_LOCALBA_REMOTEBA MODIFY SND_RECORD_FORMAT varchar(255) DEFAULT 'VARIABLE' NOT NULL
/