<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.cbi.chc.csw</groupId>
    <artifactId>chc-ccr-clientsw</artifactId>
    <version>1.10.0</version>
  </parent>
  <artifactId>chc-ccr-clientsw-retention</artifactId>
  
  <dependencies>
		
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-service</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-mq-domain</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cbi.chc.csw</groupId>
			<artifactId>chc-ccr-clientsw-db-domain</artifactId>
			<version>${project.version}</version>
		</dependency>
		
	</dependencies>


</project>